### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by eddoww** [SightstoneOfficial/LegendaryClient#203]
Keep getting this, tried numerous things, but it always happens:

http://i.imgur.com/FXI6sYG.png

What is the problem? I can't login on any account :(

**Comment by eddoww** [comment]
(2/02/2015 6:37 PM) [EXCEPTION]: A first chance exception was thrown
(2/02/2015 6:37 PM) [EXCEPTION]: StartIndex cannot be less than zero.
Parameter name: startIndex
(2/02/2015 6:37 PM) [EXCEPTION]:    at System.String.Remove(Int32 startIndex)
(2/02/2015 6:37 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2/02/2015 6:37 PM) [UNHANDLEDEXCEPTION]: StartIndex cannot be less than zero.
Parameter name: startIndex
(2/02/2015 6:37 PM) [UNHANDLEDEXCEPTION]:    at System.String.Remove(Int32 startIndex)
   at LegendaryClient.Windows.MainPage.ParseNews(BaseRegion region) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 405
   at LegendaryClient.Windows.MainPage.<>c__DisplayClass21.<GetNews>b__20(Object param0, RunWorkerCompletedEventArgs param1) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 368
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0

**Comment by eddoww** [comment]
(used both the installer, and the latest release, haven't tried compiling myself, about to do that now..)

**Comment by nairaner** [comment]
same as #202.
Wait for fix
