### ISSUE TITLE
Co-op vs. AI Champion Select Crash

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#217]
Upon entering champion select from a Coop vs AI queue, LegendaryClient immediately crashes.

```
(2/18/2015 23:12:21) [LOG]: Starting Patcher
(2/18/2015 23:12:21) [LOG]: LegendaryClient Started Up Successfully
(2/18/2015 23:12:24) [LOG]: DataDragon Version: 5.3.1
(2/18/2015 23:12:24) [LOG]: Current DataDragon Version: 5.3.1
(2/18/2015 23:12:24) [LOG]: DDragon Version (LOL Version) = 5.3.1
(2/18/2015 23:12:24) [LOG]: Client Version: 5.3.1
(2/18/2015 23:12:25) [LOG]: Air Assets Version: 0.0.1.129
(2/18/2015 23:12:25) [LOG]: Current Air Assets Version: 0.0.1.129
(2/18/2015 23:12:25) [LOG]: Trying to detect League of Legends GameClient
(2/18/2015 23:12:25) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(2/18/2015 23:12:25) [LOG]: Latest League of Legends GameClient: 0.0.1.78
(2/18/2015 23:12:26) [LOG]: Checking if League of Legends is Up-To-Date
(2/18/2015 23:12:26) [LOG]: League of Legends is not Up-To-Date. Please Update League Of Legends
(2/18/2015 23:12:26) [EXCEPTION]: A first chance exception was thrown
(2/18/2015 23:12:26) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(2/18/2015 23:12:26) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(2/18/2015 23:13:5) [EXCEPTION]: A first chance exception was thrown
(2/18/2015 23:13:5) [EXCEPTION]: An invalid IP address was specified.
(2/18/2015 23:13:5) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(2/18/2015 23:13:5) [LOG]: Connected to OCE and logged in as #Summoner#
(2/18/2015 23:13:9) [EXCEPTION]: A first chance exception was thrown
(2/18/2015 23:13:9) [EXCEPTION]: Application identity is not set.
(2/18/2015 23:13:10) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(2/18/2015 23:13:41) [EXCEPTION]: A first chance exception was thrown
(2/18/2015 23:13:41) [EXCEPTION]: Index was outside the bounds of the array.
(2/18/2015 23:13:42) [EXCEPTION]:    at LegendaryClient.Windows.ChampSelectPage.<>c__DisplayClass27.<<ChampSelect_OnMessageReceived>b__15>d__35.MoveNext()
(2/18/2015 23:13:42) [EXCEPTION]: A first chance exception was thrown
(2/18/2015 23:13:42) [EXCEPTION]: Index was outside the bounds of the array.
(2/18/2015 23:13:42) [EXCEPTION]:    at LegendaryClient.Windows.ChampSelectPage.<>c__DisplayClass27.<<ChampSelect_OnMessageReceived>b__15>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(2/18/2015 23:13:42) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2/18/2015 23:13:42) [UNHANDLEDEXCEPTION]: Index was outside the bounds of the array.
(2/18/2015 23:13:42) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Windows.ChampSelectPage.<>c__DisplayClass27.<<ChampSelect_OnMessageReceived>b__15>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()
```

**Comment by Phorofor** [comment]
Re-opened this since I now have managed to get a better version of this crash log where it doesn't happen to show other things that are irrelevant.

**Comment by nairaner** [comment]
solo queue or team queue?

**Comment by Phorofor** [comment]
I tried it for both, LegendaryClient crashes as soon as it hits up onto Champion Select.
