### ISSUE TITLE
Crash upon clicking 'Team Queue'

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#266]
When ever I want to go to the Team Queue window LegendaryClient immediately crashes upon clicking to bring up the Team Queue window.

Server: OCE

```
(3/14/2015 00:44:8) [LOG]: LegendaryClient Started Up Successfully
(3/14/2015 00:44:9) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:9) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(3/14/2015 00:44:9) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(3/14/2015 00:44:12) [LOG]: DataDragon Version: 5.5.2
(3/14/2015 00:44:12) [LOG]: Current DataDragon Version: 5.5.2
(3/14/2015 00:44:12) [LOG]: DDragon Version (LOL Version) = 5.5.2
(3/14/2015 00:44:12) [LOG]: Air Assets Version: 0.0.1.134
(3/14/2015 00:44:12) [LOG]: Current Air Assets Version: 0.0.1.134
(3/14/2015 00:44:16) [LOG]: Checking Theme...
(3/14/2015 00:44:16) [LOG]: Trying to detect League of Legends GameClient
(3/14/2015 00:44:16) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(3/14/2015 00:44:16) [LOG]: Latest League of Legends GameClient: 0.0.1.80
(3/14/2015 00:44:16) [LOG]: Checking if League of Legends is Up-To-Date
(3/14/2015 00:44:16) [LOG]: League of Legends is Up-To-Date
(3/14/2015 00:44:17) [LOG]: LegendaryClient Has Finished Patching
(3/14/2015 00:44:36) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:36) [EXCEPTION]: Member not found.
(3/14/2015 00:44:36) [EXCEPTION]:    at System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
(3/14/2015 00:44:36) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:36) [EXCEPTION]: Type PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[] not supported by flash serializer
(3/14/2015 00:44:36) [EXCEPTION]:    at PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\PVPNetConnect\RiotObjects\RiotGamesObject.cs:line 294
(3/14/2015 00:44:39) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:39) [EXCEPTION]: An invalid IP address was specified.
(3/14/2015 00:44:39) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/14/2015 00:44:39) [LOG]: Connected to OCE and logged in as Abdominals
(3/14/2015 00:44:44) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:44) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/14/2015 00:44:44) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/14/2015 00:44:50) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:50) [EXCEPTION]: Application identity is not set.
(3/14/2015 00:44:50) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(3/14/2015 00:44:53) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:44:53) [EXCEPTION]: The method or operation is not implemented.
(3/14/2015 00:44:53) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
(3/14/2015 00:44:58) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/OC1/82201940/200617492?tab=overview
(3/14/2015 00:45:10) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:45:10) [EXCEPTION]: The method or operation is not implemented.
(3/14/2015 00:45:10) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
(3/14/2015 00:45:10) [EXCEPTION]: A first chance exception was thrown
(3/14/2015 00:45:10) [EXCEPTION]: The method or operation is not implemented.
(3/14/2015 00:45:10) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
   at LegendaryClient.Windows.TeamQueuePage.PingElapsed(Object sender, ElapsedEventArgs e) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 180
   at LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__1.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(3/14/2015 00:45:11) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/14/2015 00:45:11) [UNHANDLEDEXCEPTION]: The method or operation is not implemented.
(3/14/2015 00:45:12) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
   at LegendaryClient.Windows.TeamQueuePage.PingElapsed(Object sender, ElapsedEventArgs e) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 180
   at LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__1.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0
```

**Comment by secretdataz** [comment]
Fixed in b73f610
