### ISSUE TITLE
Crash with Garena

### ISSUE THREAD

**Issue by baprang** [SightstoneOfficial/LegendaryClient#276]
-Chat not work, not show friends.
-Profile display level 0
-Overview, Legues, Match history not work
-Join queue
My logs
(16/03/2015 9:23 AM) [LOG]: LegendaryClient Started Up Successfully
(16/03/2015 9:23 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:23 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(16/03/2015 9:23 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(16/03/2015 9:23 AM) [LOG]: DataDragon Version: 5.5.2
(16/03/2015 9:23 AM) [LOG]: Current DataDragon Version: 5.5.2
(16/03/2015 9:23 AM) [LOG]: DDragon Version (LOL Version) = 5.5.2
(16/03/2015 9:23 AM) [LOG]: Air Assets Version: 0.0.1.134
(16/03/2015 9:23 AM) [LOG]: Current Air Assets Version: 0.0.1.134
(16/03/2015 9:23 AM) [LOG]: Checking Theme...
(16/03/2015 9:23 AM) [LOG]: Trying to detect League of Legends GameClient
(16/03/2015 9:23 AM) [LOG]: League of Legends is located at: D:\LienMinhHuyenThoai\GameData\Apps\lolVN\lol.exe
(16/03/2015 9:23 AM) [LOG]: Latest League of Legends GameClient: 0.0.1.80
(16/03/2015 9:23 AM) [LOG]: Checking if League of Legends is Up-To-Date
(16/03/2015 9:23 AM) [LOG]: League of Legends is Up-To-Date
(16/03/2015 9:23 AM) [LOG]: LegendaryClient Has Finished Patching
(16/03/2015 9:23 AM) [LOG]: Recieved token, it is: MVzoxU0rZXqdE9/Z6FpgJ27T2wERBTz90kPpB4lAqPHmLUxAkFhxNxEWPb+h9wcv2mHnZAGi1TVI/fRwFCuvtI/HehvyI8SkUx55LP8B/NESF+NlWeOeXFu643GlqxBtq+mWJvX6lLo9Km9gPBOK0UcKJxAd5e8+eoo/G5lIOIfb7rDt5Rrbqw1CAezmn2VHMJ4IFvzMsyqB952N5sEL4C++9nvz3WY2aBPYtREs1XJvYtjghN/qQcIRXlcH3wOjmNt0hJI+nFJkFtAP72+NZ+TwGrG/5EcmYdQVNEiQZ44NIXSV5X/mG01frP/RLFzYzlYe9g/7cTrZQoOt7DUq5A==
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Member not found.
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Type PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[] not supported by flash serializer
(16/03/2015 9:24 AM) [EXCEPTION]:    at PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) in c:\Users\Betty\Desktop\Coding\LegendaryClient\PVPNetConnect\RiotObjects\RiotGamesObject.cs:line 294
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: An invalid IP address was specified.
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(16/03/2015 9:24 AM) [LOG]: Connected to  and logged in as MR_BrZp
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Could not find file 'C:\LegenadryClient\RunePages\MR_BrZp'.
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:24 AM) [EXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:24 AM) [EXCEPTION]:    at LegendaryClient.Windows.MainPage.<>c__DisplayClass30.<ChangeSpectatorRegion>b__2c(Object param0, DoWorkEventArgs param1) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 486
(16/03/2015 9:24 AM) [EXCEPTION]:    at LegendaryClient.Windows.MainPage.<>c__DisplayClass29.<GetNews>b__27(Object param0, DoWorkEventArgs param1) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 364
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:24 AM) [EXCEPTION]:    at LegendaryClient.Logic.Region.BaseRegion.GetRegion(String requestedRegion) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\BaseRegion.cs:line 37
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:24 AM) [EXCEPTION]:    at LegendaryClient.Logic.Region.BaseRegion.GetRegion(String requestedRegion) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\BaseRegion.cs:line 37
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 203.162.171.143:5223
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(16/03/2015 9:24 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:24 AM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/03/2015 9:24 AM) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(16/03/2015 9:25 AM) [EXCEPTION]: A first chance exception was thrown
(16/03/2015 9:25 AM) [EXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:25 AM) [EXCEPTION]:    at LegendaryClient.Windows.Profile.Leagues.RenderLeague() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\Profile\Leagues.xaml.cs:line 65
(16/03/2015 9:25 AM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(16/03/2015 9:25 AM) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(16/03/2015 9:25 AM) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Windows.Profile.Leagues.RenderLeague() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\Profile\Leagues.xaml.cs:line 65
   at LegendaryClient.Windows.Profile.Leagues.UpTierButton_Click(Object sender, RoutedEventArgs e) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\Profile\Leagues.xaml.cs:line 171
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0

**Comment by secretdataz** [comment]
Could not reproduce.
What rank are you in? unranked?

**Comment by nairaner** [comment]
Same as #202 need to ask dispersia about status

**Comment by NitroXenon** [comment]
Did you click any button in League page?

**Comment by nairaner** [comment]
does it still happen on newest dev build?
