### ISSUE TITLE
Team Queue option still causing crash. (OCE server only?)

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#278]
I don't know if it's just the Oceania server that's making this option messed up but when I use the Team Queue option on a server such as Europe West it works without a crash.

Using Release: 2.3.0.1

```
(3/16/2015 16:37:36) [LOG]: LegendaryClient Started Up Successfully
(3/16/2015 16:37:36) [LOG]: DataDragon Version: 5.5.2
(3/16/2015 16:37:36) [LOG]: Current DataDragon Version: 5.5.2
(3/16/2015 16:37:36) [LOG]: DDragon Version (LOL Version) = 5.5.2
(3/16/2015 16:37:38) [LOG]: Air Assets Version: 0.0.1.134
(3/16/2015 16:37:38) [LOG]: Current Air Assets Version: 0.0.1.134
(3/16/2015 16:37:39) [LOG]: Checking Theme...
(3/16/2015 16:37:39) [LOG]: Trying to detect League of Legends GameClient
(3/16/2015 16:37:39) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(3/16/2015 16:37:39) [LOG]: Latest League of Legends GameClient: 0.0.1.80
(3/16/2015 16:37:39) [LOG]: Checking if League of Legends is Up-To-Date
(3/16/2015 16:37:39) [LOG]: League of Legends is Up-To-Date
(3/16/2015 16:37:39) [LOG]: LegendaryClient Has Finished Patching
(3/16/2015 16:38:27) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:27) [EXCEPTION]: An invalid IP address was specified.
(3/16/2015 16:38:28) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/16/2015 16:38:28) [LOG]: Connected to OCE and logged in as Abdominals
(3/16/2015 16:38:28) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:28) [EXCEPTION]: Could not find file 'C:\LegendaryClient\RunePages\Abdominals'.
(3/16/2015 16:38:28) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(3/16/2015 16:38:30) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:30) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/16/2015 16:38:30) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/16/2015 16:38:31) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:31) [EXCEPTION]: Application identity is not set.
(3/16/2015 16:38:31) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(3/16/2015 16:38:38) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/OC1/82459756/200617492?tab=overview
(3/16/2015 16:38:48) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:48) [EXCEPTION]: The method or operation is not implemented.
(3/16/2015 16:38:48) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
(3/16/2015 16:38:53) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:53) [EXCEPTION]: The method or operation is not implemented.
(3/16/2015 16:38:53) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
(3/16/2015 16:38:53) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 16:38:53) [EXCEPTION]: The method or operation is not implemented.
(3/16/2015 16:38:53) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
   at LegendaryClient.Windows.TeamQueuePage.PingElapsed(Object sender, ElapsedEventArgs e) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 180
   at LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__1.MoveNext() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(3/16/2015 16:38:53) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/16/2015 16:38:53) [UNHANDLEDEXCEPTION]: The method or operation is not implemented.
(3/16/2015 16:38:54) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
   at LegendaryClient.Windows.TeamQueuePage.PingElapsed(Object sender, ElapsedEventArgs e) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 180
   at LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__1.MoveNext() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0
```

**Comment by secretdataz** [comment]
Hello, thanks for reporting this. Hopefully the latest commit will fix this.
You can get the latest EXE at ~~removed link~~ use CI instead. ~~because there are some problem with CI atm~~.
Terms on README.md about this still applies. ;)

Edit : CI is now working

**Comment by Phorofor** [comment]
YES! It's working fine now (avast! for some reason refused to download the file had to turn it off temporarily, but the exe itself is all good).

Thank you for the fix, have a good day.

**Comment by secretdataz** [comment]
Hehe, I'm the one who broke it. You, Have a good day, too.
