### ISSUE TITLE
Garena crashed while selecting masteries

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#279]
(2015/3/16 下午 06:14) [LOG]: LegendaryClient Started Up Successfully
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. 系統找不到指定的檔案。
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(2015/3/16 下午 06:14) [LOG]: DataDragon Version: 5.5.2
(2015/3/16 下午 06:14) [LOG]: Current DataDragon Version: 5.5.2
(2015/3/16 下午 06:14) [LOG]: DDragon Version (LOL Version) = 5.5.2
(2015/3/16 下午 06:14) [LOG]: Air Assets Version: 0.0.1.134
(2015/3/16 下午 06:14) [LOG]: Current Air Assets Version: 0.0.1.134
(2015/3/16 下午 06:14) [LOG]: Checking Theme...
(2015/3/16 下午 06:14) [LOG]: Trying to detect League of Legends GameClient
(2015/3/16 下午 06:14) [LOG]: League of Legends is located at: E:\Program Files (x86)\GarenaLoLTW\GameData\Apps\LoLTW\
(2015/3/16 下午 06:14) [LOG]: Latest League of Legends GameClient: 0.0.1.80
(2015/3/16 下午 06:14) [LOG]: Checking if League of Legends is Up-To-Date
(2015/3/16 下午 06:14) [LOG]: League of Legends is Up-To-Date
(2015/3/16 下午 06:14) [LOG]: LegendaryClient Has Finished Patching
(2015/3/16 下午 06:14) [LOG]: Received token, it is: ieG7uICjENvGdBmrElxUq58OD/b3pED5hC/V46EMmDOg9hxZ79OqTu1ExAlzoUpFeepMov61wtW/aQYhFIPI4vLv0npijYQYFkJcwrYqykK3/Tujs4Mc0h+8Rng8owxwVCi5E3aK4atFvoZySe9O8TBGrdCBcI6tmj6y0K0ny7s+RQI8qiWLpfmZfJLqIxxCkhh+VGCVNqVLleFgbfpOr2DsRTiYq2iGxThA4/OSrBMrPtp0McIkMOJqzqPBRDU+kneAqwBRwqYd1VKbdLTUVqh9p4rFom1L6okjIHsLcUEJ6lE49GX81AoC9RZd/pebf2RZLgstPEQ6ZygSdO8FVg==
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: Member not found.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: Type PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[] not supported by flash serializer
(2015/3/16 下午 06:14) [EXCEPTION]:    at PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) in c:\projects\legendaryclient\PVPNetConnect\RiotObjects\RiotGamesObject.cs:line 294
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: An invalid IP address was specified.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(2015/3/16 下午 06:14) [LOG]: Connected to tw and logged in as tabyw1259
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: Could not find file 'E:\Program Files (x86)\GarenaLoLTW\LegendaryClient\bin\Release\RunePages\tabyw1259'.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: Invalid JSON primitive: .
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(2015/3/16 下午 06:14) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(2015/3/16 下午 06:14) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/TW/806632095/4670189?tab=overview
(2015/3/16 下午 06:14) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:14) [EXCEPTION]: The method or operation is not implemented.
(2015/3/16 下午 06:14) [EXCEPTION]:    at LegendaryClient.Logic.Region.Garena.TW.get_PingAddresses() in c:\projects\legendaryclient\LegendaryClient\Logic\Region\Garena\TW.cs:line 57
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: 遠端主機已強制關閉一個現存的連線。
(2015/3/16 下午 06:15) [EXCEPTION]: 連線已被您主機上的軟體中止。
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to read data from the transport connection: 連線已被您主機上的軟體中止。.
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to read data from the transport connection: 連線已被您主機上的軟體中止。.
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
(2015/3/16 下午 06:15) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [EXCEPTION]:    at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs:line 756
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [EXCEPTION]:    at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs:line 756
   at PVPNetConnect.PVPNetConnection.<SaveMasteryBook>d__1c1.MoveNext() in c:\projects\legendaryclient\PVPNetConnect\PublicMethods.cs:line 1255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(2015/3/16 下午 06:15) [EXCEPTION]: A first chance exception was thrown
(2015/3/16 下午 06:15) [EXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [EXCEPTION]:    at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs:line 756
   at PVPNetConnect.PVPNetConnection.<SaveMasteryBook>d__1c1.MoveNext() in c:\projects\legendaryclient\PVPNetConnect\PublicMethods.cs:line 1255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryClient.Windows.ChampSelectPage.<MasteryComboBox_SelectionChanged>d__86.MoveNext() in c:\projects\legendaryclient\LegendaryClient\Windows\ChampSelectPage.xaml.cs:line 1386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(2015/3/16 下午 06:15) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2015/3/16 下午 06:15) [UNHANDLEDEXCEPTION]: Unable to write data to the transport connection: 遠端主機已強制關閉一個現存的連線。.
(2015/3/16 下午 06:15) [UNHANDLEDEXCEPTION]:    at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs:line 756
   at PVPNetConnect.PVPNetConnection.<SaveMasteryBook>d__1c1.MoveNext() in c:\projects\legendaryclient\PVPNetConnect\PublicMethods.cs:line 1255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryClient.Windows.ChampSelectPage.<MasteryComboBox_SelectionChanged>d__86.MoveNext() in c:\projects\legendaryclient\LegendaryClient\Windows\ChampSelectPage.xaml.cs:line 1386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\projects\legendaryclient\LegendaryClient\obj\Release\App.g.cs:line 0

Any idea? It seems to be the problem of PVPConnect.

**Comment by nairaner** [comment]
I guess its problem with coding asian character in rtmp, will look into it when im home

**Comment by NitroXenon** [comment]
Ok thx a lot. Gonna test mastery page in non-English name.

**Comment by NitroXenon** [comment]
@nairaner Not really the problem of asian characters. I changed the name of the mastery page to English using official client but LC also crashed when I was changing masteris page.
