### ISSUE TITLE
Co-op vs. AI Enter Champion Select crash

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#282]
LegendaryClient crashes upon entering champion select in Co-op vs. AI. 
Don't know if it's a OCE specific thing or something but it looks like it mentions something about OCE down in the log somewhere.

Using commit: 3be8752741 but this crashing was happening previously.

```
(3/16/2015 22:53:24) [LOG]: LegendaryClient Started Up Successfully
(3/16/2015 22:53:33) [LOG]: DataDragon Version: 5.5.2
(3/16/2015 22:53:33) [LOG]: Current DataDragon Version: 5.5.2
(3/16/2015 22:53:33) [LOG]: DDragon Version (LOL Version) = 5.5.2
(3/16/2015 22:53:33) [LOG]: Air Assets Version: 0.0.1.134
(3/16/2015 22:53:33) [LOG]: Current Air Assets Version: 0.0.1.134
(3/16/2015 22:53:35) [LOG]: Checking Theme...
(3/16/2015 22:53:36) [LOG]: Trying to detect League of Legends GameClient
(3/16/2015 22:53:36) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(3/16/2015 22:53:36) [LOG]: Latest League of Legends GameClient: 0.0.1.80
(3/16/2015 22:53:36) [LOG]: Checking if League of Legends is Up-To-Date
(3/16/2015 22:53:36) [LOG]: League of Legends is Up-To-Date
(3/16/2015 22:53:36) [LOG]: LegendaryClient Has Finished Patching
(3/16/2015 22:54:27) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:54:27) [EXCEPTION]: An invalid IP address was specified.
(3/16/2015 22:54:27) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/16/2015 22:54:27) [LOG]: Connected to OCE and logged in as #SUMMONER_NAME#
(3/16/2015 22:54:28) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:54:28) [EXCEPTION]: Could not find file 'C:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\bin\Debug\RunePages\#SUMMONER_NAME#'.
(3/16/2015 22:54:28) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(3/16/2015 22:54:30) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:54:30) [EXCEPTION]: Application identity is not set.
(3/16/2015 22:54:30) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(3/16/2015 22:54:31) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:54:31) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/16/2015 22:54:31) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/16/2015 22:54:39) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/OC1/82595190/200617492?tab=overview
(3/16/2015 22:54:55) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:54:55) [EXCEPTION]: The method or operation is not implemented.
(3/16/2015 22:54:55) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Logic\Region\OCE.cs:line 56
(3/16/2015 22:55:6) [LOG]: Now in Queue
(3/16/2015 22:55:34) [LOG]: Now in Queue
(3/16/2015 22:56:1) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:56:1) [EXCEPTION]: Value cannot be null.
Parameter name: source
(3/16/2015 22:56:1) [EXCEPTION]:    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
(3/16/2015 22:56:1) [EXCEPTION]: A first chance exception was thrown
(3/16/2015 22:56:1) [EXCEPTION]: Value cannot be null.
Parameter name: source
(3/16/2015 22:56:1) [EXCEPTION]:    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at LegendaryClient.Windows.ChampSelectPage.<>c__DisplayClass27.<<ChampSelect_OnMessageReceived>b__15>d__35.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\ChampSelectPage.xaml.cs:line 696
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(3/16/2015 22:56:2) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/16/2015 22:56:2) [UNHANDLEDEXCEPTION]: Value cannot be null.
Parameter name: source
(3/16/2015 22:56:2) [UNHANDLEDEXCEPTION]:    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at LegendaryClient.Windows.ChampSelectPage.<>c__DisplayClass27.<<ChampSelect_OnMessageReceived>b__15>d__35.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\ChampSelectPage.xaml.cs:line 696
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
```

**Comment by eddy5641** [comment]
Update and try

**Comment by secretdataz** [comment]
Inactive or no feedback.
