### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#304]
Screenshot :
https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t35.0-12/11080614_841164189276593_4358001534411328065_o.jpg?oh=61d14157593ec779a3ca1c41a3365baa&oe=550D4A4E&__gda__=1426936689_8f59bdbf864a53b5c08f3e6d6d5088ca

Logs :
(2015/3/18 下午 08:41) [LOG]: LegendaryClient Started Up Successfully
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: A call to SSPI failed, see inner exception.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: A call to SSPI failed, see inner exception.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: A call to SSPI failed, see inner exception.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: A call to SSPI failed, see inner exception.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: Safe handle has been closed
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.Net.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding_SECURITY(SafeDeleteContext phContext, ContextAttribute contextAttribute, Bindings\* buffer, SafeFreeContextBufferChannelBinding refHandle)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
(2015/3/18 下午 08:41) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 08:41) [EXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(2015/3/18 下午 08:41) [EXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at LegendaryClient.Windows.PatcherPage.<StartPatcher>d__c.MoveNext() in c:\projects\legendaryclient\LegendaryClient\Windows\PatcherPage.xaml.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(2015/3/18 下午 08:41) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2015/3/18 下午 08:41) [UNHANDLEDEXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(2015/3/18 下午 08:41) [UNHANDLEDEXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at LegendaryClient.Windows.PatcherPage.<StartPatcher>d__c.MoveNext() in c:\projects\legendaryclient\LegendaryClient\Windows\PatcherPage.xaml.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\projects\legendaryclient\LegendaryClient\obj\Release\App.g.cs:line 0

**Comment by eddy5641** [comment]
try run as admin

**Comment by NitroXenon** [comment]
@eddy5641 yes ran LC as admin... 64bit

P.S. this is not my LC, I ask for my friend.

**Comment by nongnoobjung** [comment]
@NitroXenon 
try this method 
https://www.joduska.me/forum/topic/10313-wip-legendaryclient/?p=516138

**Comment by nairaner** [comment]
Might have fixed it in 60554fc591ff0936bf11694935899e1b81cf9dc8
