### ISSUE TITLE
OCE Client Crash upon login

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#313]
Logged into OCE and it crashed the client. Checked to see if it affecting other servers such as EUW but it works without a crash, so it must just be OCE stuff again.

Using commit: caef78654a

```
(3/21/2015 09:55:39) [LOG]: LegendaryClient Started Up Successfully
(3/21/2015 09:55:39) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:39) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(3/21/2015 09:55:39) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(3/21/2015 09:55:40) [LOG]: Newest DataDragon Version: 5.5.3
(3/21/2015 09:55:40) [LOG]: Current DataDragon Version: 5.5.3
(3/21/2015 09:55:41) [LOG]: DDragon Version (LOL Version) = 5.5.3
(3/21/2015 09:55:41) [LOG]: Newest Air Assets Version: 0.0.1.134
(3/21/2015 09:55:41) [LOG]: Current Air Assets Version: 0.0.1.134
(3/21/2015 09:55:42) [LOG]: Checking Theme...
(3/21/2015 09:55:42) [LOG]: Trying to detect League of Legends GameClient
(3/21/2015 09:55:42) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(3/21/2015 09:55:42) [LOG]: Latest League of Legends GameClient: 0.0.1.81
(3/21/2015 09:55:42) [LOG]: Checking if League of Legends is Up-To-Date
(3/21/2015 09:55:42) [LOG]: League of Legends is Up-To-Date
(3/21/2015 09:55:42) [LOG]: LegendaryClient Has Finished Patching
(3/21/2015 09:55:55) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:55) [EXCEPTION]: An invalid IP address was specified.
(3/21/2015 09:55:55) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/21/2015 09:55:55) [LOG]: Connected to OCE and logged in as #SUMMONER#
(3/21/2015 09:55:55) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:55) [EXCEPTION]: Could not find a part of the path 'C:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\bin\Debug\RunePages#SUMMONER#'.
(3/21/2015 09:55:55) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(3/21/2015 09:55:56) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:56) [EXCEPTION]: Application identity is not set.
(3/21/2015 09:55:56) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(3/21/2015 09:55:57) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:57) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/21/2015 09:55:57) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/21/2015 09:55:58) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:58) [EXCEPTION]: Object reference not set to an instance of an object.
(3/21/2015 09:55:58) [EXCEPTION]:    at LegendaryClient.Windows.Profile.Leagues.<>c__DisplayClass14.<GotStats>b__10() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\Profile\Leagues.xaml.cs:line 224
(3/21/2015 09:55:58) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 09:55:58) [EXCEPTION]: Exception has been thrown by the target of an invocation.
(3/21/2015 09:55:58) [EXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
(3/21/2015 09:55:58) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/21/2015 09:55:59) [UNHANDLEDEXCEPTION]: Exception has been thrown by the target of an invocation.
(3/21/2015 09:55:59) [UNHANDLEDEXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
```

**Comment by nairaner** [comment]
try deleting files in RunePages folder

**Comment by Phorofor** [comment]
Deleted what ever was in that folder, but client still crashes upon logging in.

**Comment by secretdataz** [comment]
Same issue here.
http://pastebin.com/0diuxr0j

**Comment by nairaner** [comment]
should work in latest build

**Comment by Phorofor** [comment]
Crashes still persists. There seems to be something about BroadcastMessage this time.

```
(3/21/2015 21:58:46) [LOG]: LegendaryClient Started Up Successfully
(3/21/2015 21:58:46) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 21:58:46) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=#TOKEN# or one of its dependencies. The system cannot find the file specified.
(3/21/2015 21:58:46) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(3/21/2015 21:58:47) [LOG]: Newest DataDragon Version: 5.5.3
(3/21/2015 21:58:47) [LOG]: Current DataDragon Version: 5.5.3
(3/21/2015 21:58:47) [LOG]: DDragon Version (LOL Version) = 5.5.3
(3/21/2015 21:58:48) [LOG]: Newest Air Assets Version: 0.0.1.134
(3/21/2015 21:58:48) [LOG]: Current Air Assets Version: 0.0.1.134
(3/21/2015 21:58:51) [LOG]: Checking Theme...
(3/21/2015 21:58:51) [LOG]: Trying to detect League of Legends GameClient
(3/21/2015 21:58:51) [LOG]: League of Legends is located at: C:\Riot Games\League Of Legends\
(3/21/2015 21:58:51) [LOG]: Latest League of Legends GameClient: 0.0.1.81
(3/21/2015 21:58:51) [LOG]: Checking if League of Legends is Up-To-Date
(3/21/2015 21:58:51) [LOG]: League of Legends is Up-To-Date
(3/21/2015 21:58:51) [LOG]: LegendaryClient Has Finished Patching
(3/21/2015 22:00:10) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:11) [EXCEPTION]: Member not found.
(3/21/2015 22:00:11) [EXCEPTION]:    at System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
(3/21/2015 22:00:11) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:11) [EXCEPTION]: Type PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[] not supported by flash serializer
(3/21/2015 22:00:11) [EXCEPTION]:    at PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\PVPNetConnect\RiotObjects\RiotGamesObject.cs:line 296
(3/21/2015 22:00:13) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:13) [EXCEPTION]: An invalid IP address was specified.
(3/21/2015 22:00:13) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/21/2015 22:00:13) [LOG]: Connected to OCE and logged in as #SUMMONER#
(3/21/2015 22:00:14) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:14) [EXCEPTION]: Could not find a part of the path 'C:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\bin\Debug\RunePages#SUMMONER#'.
(3/21/2015 22:00:14) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(3/21/2015 22:00:15) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:15) [EXCEPTION]: Length cannot be less than zero.
Parameter name: length
(3/21/2015 22:00:15) [EXCEPTION]:    at System.String.Substring(Int32 startIndex, Int32 length)
(3/21/2015 22:00:15) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:15) [EXCEPTION]: Length cannot be less than zero.
Parameter name: length
(3/21/2015 22:00:15) [EXCEPTION]:    at System.String.Substring(Int32 startIndex, Int32 length)
   at LegendaryClient.Windows.MainPage.ConvertBoostTime(Double unixTimeStamp) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 256
   at LegendaryClient.Windows.MainPage.<UpdateSummonerInformation>d__13.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(3/21/2015 22:00:16) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/21/2015 22:00:16) [UNHANDLEDEXCEPTION]: Length cannot be less than zero.
Parameter name: length
(3/21/2015 22:00:16) [UNHANDLEDEXCEPTION]:    at System.String.Substring(Int32 startIndex, Int32 length)
   at LegendaryClient.Windows.MainPage.ConvertBoostTime(Double unixTimeStamp) in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 256
   at LegendaryClient.Windows.MainPage.<UpdateSummonerInformation>d__13.MoveNext() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\#USER#\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
(3/21/2015 22:00:17) [EXCEPTION]: A first chance exception was thrown
(3/21/2015 22:00:17) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/21/2015 22:00:17) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
```

**Comment by secretdataz** [comment]
That was another issue. Thanks for the report though.
