### ISSUE TITLE
2.3.0.117 Crash when get invited

### ISSUE THREAD

**Issue by pondtroid** [SightstoneOfficial/LegendaryClient#318]
freeze and crash when get invited to join game room

**Comment by secretdataz** [comment]
Can confirm.
On Garena TH server

**Comment by nairaner** [comment]
can you upload log?

**Comment by pondtroid** [comment]
(21/3/2558 21:35) [LOG]: LegendaryClient Started Up Successfully
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(21/3/2558 21:35) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(21/3/2558 21:35) [LOG]: Newest DataDragon Version: 5.5.3
(21/3/2558 21:35) [LOG]: Current DataDragon Version: 5.5.3
(21/3/2558 21:35) [LOG]: DDragon Version (LOL Version) = 5.5.3
(21/3/2558 21:35) [LOG]: Newest Air Assets Version: 0.0.1.134
(21/3/2558 21:35) [LOG]: Current Air Assets Version: 0.0.1.134
(21/3/2558 21:35) [LOG]: Checking Theme...
(21/3/2558 21:35) [LOG]: Trying to detect League of Legends GameClient
(21/3/2558 21:35) [LOG]: League of Legends is located at: D:\GarenaLoLTH_20150121\GarenaLoLTH\GameData\Apps\LoLTH\
(21/3/2558 21:35) [LOG]: Latest League of Legends GameClient: 0.0.1.81
(21/3/2558 21:35) [LOG]: Checking if League of Legends is Up-To-Date
(21/3/2558 21:35) [LOG]: League of Legends is Up-To-Date
(21/3/2558 21:35) [LOG]: LegendaryClient Has Finished Patching
(21/3/2558 21:35) [LOG]: Received token, it is: JoSfongLN1YYZOV2FL+1d2svmEA7+io7eCu1NpwggHghgtufXWGLOZjAk+2G27U2VH8aAgECzKB7/nTW/TERtwlk2eCpaETJSgSD21f+XS5SdNLBtOFoFdJXnFryj3GMBZxusJFplIqXnmnVueuzc7wIyHXJwAkcF5tPH7q56YOjh8+zXzhbo5y9IgpAjAQBYDE0NYZL+H3vvJaTaiZdrAcxd6Tig3uEQr4BNQ6Ogz6L6ibgmm3dnJ+/ZPLk9oM73RvoTOSCoS/IHRDNmFQAGgsQGeXZsZ0k88fBWYGYk8pRVgZxySx/BY7U1wi4FOBoI8EQJwJBTWpV6==
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: An invalid IP address was specified.
(21/3/2558 21:35) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(21/3/2558 21:35) [LOG]: Connected to th and logged in as 
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(21/3/2558 21:35) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(21/3/2558 21:35) [EXCEPTION]:    at xpnet.Encoding.scanEndTag(Byte[] buf, Int32 off, Int32 end, Token token)
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: Arithmetic operation resulted in an overflow.
(21/3/2558 21:35) [EXCEPTION]:    at System.Double.System.IConvertible.ToInt64(IFormatProvider provider)
(21/3/2558 21:35) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/TH/xxxxx/xxxxxxx?tab=overview
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
(21/3/2558 21:35) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(21/3/2558 21:35) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:35) [EXCEPTION]: Invalid JSON primitive: .
(21/3/2558 21:35) [EXCEPTION]:    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
(21/3/2558 21:36) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:36) [EXCEPTION]: The given key was not present in the dictionary.
(21/3/2558 21:36) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(21/3/2558 21:36) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:36) [EXCEPTION]: The given key was not present in the dictionary.
(21/3/2558 21:36) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(21/3/2558 21:36) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:36) [EXCEPTION]: Object reference not set to an instance of an object.
(21/3/2558 21:36) [EXCEPTION]:    at LegendaryClient.Logic.Client.<>c__DisplayClass34.<>c__DisplayClass36.<OnMessageReceived>b__32()
(21/3/2558 21:36) [EXCEPTION]: A first chance exception was thrown
(21/3/2558 21:36) [EXCEPTION]: Exception has been thrown by the target of an invocation.
(21/3/2558 21:36) [EXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
(21/3/2558 21:36) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(21/3/2558 21:36) [UNHANDLEDEXCEPTION]: Exception has been thrown by the target of an invocation.
(21/3/2558 21:36) [UNHANDLEDEXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()
