### ISSUE TITLE
crash when creating custom

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#321]
```
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: Unable to cast object of type 'RtmpSharp.IO.AsObject' to type 'LegendaryClient.Logic.Riot.com.riotgames.platform.gameinvite.contract.Member'.
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: The value "RtmpSharp.IO.AsObject" is not of type "LegendaryClient.Logic.Riot.com.riotgames.platform.gameinvite.contract.Member" and cannot be used in this generic collection.
Parameter name: value
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType)
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: Thread was being aborted.
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: Thread was being aborted.
(3/22/2015 8:30 PM) [EXCEPTION]: Exception of type 'RtmpSharp.Net.ClientDisconnectedException' was thrown.
(3/22/2015 8:30 PM) [EXCEPTION]: Thread was being aborted.
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(3/22/2015 8:30 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketReader.ReadLoop()
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:30 PM) [EXCEPTION]: Thread was being aborted.
(3/22/2015 8:30 PM) [EXCEPTION]: Exception of type 'RtmpSharp.Net.ClientDisconnectedException' was thrown.
(3/22/2015 8:30 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketWriter.WriteLoop()
(3/22/2015 8:30 PM) [EXCEPTION]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<InvokeAsync>d__2a`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(3/22/2015 8:32 PM) [EXCEPTION]: A first chance exception was thrown
(3/22/2015 8:32 PM) [EXCEPTION]: Exception of type 'RtmpSharp.Net.ClientDisconnectedException' was thrown.
(3/22/2015 8:32 PM) [EXCEPTION]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<InvokeAsync>d__2a`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LegendaryClient.Windows.CreateCustomGamePage.<CreateGameButton_Click>d__0.MoveNext() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\CreateCustomGamePage.xaml.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(3/22/2015 8:32 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(3/22/2015 8:32 PM) [UNHANDLEDEXCEPTION]: Exception of type 'RtmpSharp.Net.ClientDisconnectedException' was thrown.
(3/22/2015 8:32 PM) [UNHANDLEDEXCEPTION]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<InvokeAsync>d__2a`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LegendaryClient.Windows.CreateCustomGamePage.<CreateGameButton_Click>d__0.MoveNext() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\LegendaryClient\Windows\CreateCustomGamePage.xaml.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LegendaryClient.App.Main() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by eddy5641** [comment]
fixed
