### ISSUE TITLE
Cant not play URF mode 

### ISSUE THREAD

**Issue by letankhanh** [SightstoneOfficial/LegendaryClient#334]
Everytime i am in queue in URF Mode ( Bot and Normal) it said " LC has stopped working"

**Comment by letankhanh** [comment]
Here is the log file
(03/04/2015 12:18 PM) [LOG]: LegendaryClient Started Up Successfully
(03/04/2015 12:18 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(03/04/2015 12:18 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:18 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(03/04/2015 12:18 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(03/04/2015 12:18 PM) [LOG]: Newest DataDragon Version: 5.6.1
(03/04/2015 12:18 PM) [LOG]: Current DataDragon Version: 5.6.1
(03/04/2015 12:18 PM) [LOG]: DDragon Version (LOL Version) = 5.6.1
(03/04/2015 12:18 PM) [LOG]: Newest Air Assets Version: 0.0.1.138
(03/04/2015 12:18 PM) [LOG]: Current Air Assets Version: 0.0.1.138
(03/04/2015 12:18 PM) [LOG]: Checking Theme...
(03/04/2015 12:18 PM) [LOG]: Trying to detect League of Legends GameClient
(03/04/2015 12:18 PM) [LOG]: League of Legends is located at: D:\Game\LienMinhHuyenThoai\LienMinhHuyenThoai\GameData\Apps\lolVN\
(03/04/2015 12:18 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.84
(03/04/2015 12:18 PM) [LOG]: Checking if League of Legends is Up-To-Date
(03/04/2015 12:18 PM) [LOG]: League of Legends is Up-To-Date
(03/04/2015 12:18 PM) [LOG]: LegendaryClient Has Finished Patching
(03/04/2015 12:18 PM) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(03/04/2015 12:19 PM) [LOG]: Received token, it is: uX8vBPuniFfnsOa4qfUgYx3Ylp2RQIZq/Cv4UP/Z0Y0l3ot+HS+ZiEzScmhq8I7VVr2Eaq51YsMUu4uvSFZIeGCzXbU3/q2RiLUi8XD4TQPENXGG74RHxByz7c/jzUZgmINGvbsCnoxvxn79rwYykY8HPHyxcSJH/+ZSmIqVJ2t6hd8iQQACh4ls5RdMhSsvRR4uYeBb/Q+UaXrG6Zd6Dw8l5xeY0o5EiePnARqoea17GEuOkjL+tl3ln6Fp5AsjOKHdke0MPj1xs5uhgL3O8ho7CsTjJKOQ0ok7fNRYDhIwC7/zOH8HkxxLC9f4kKEPl5rFxTvOfwDRyHTsEez3YA==
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: An invalid IP address was specified.
(03/04/2015 12:19 PM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(03/04/2015 12:19 PM) [LOG]: Connected to VN and logged in as K.Danny
(03/04/2015 12:19 PM) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
(03/04/2015 12:19 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(03/04/2015 12:19 PM) [EXCEPTION]:    at xpnet.Encoding.scanEndTag(Byte[] buf, Int32 off, Int32 end, Token token)
(03/04/2015 12:19 PM) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: Invalid JSON primitive: .
(03/04/2015 12:19 PM) [EXCEPTION]:    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/VN/882357832/31689938?tab=overview
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: URF
(03/04/2015 12:19 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PlayPage
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: The method or operation is not implemented.
(03/04/2015 12:19 PM) [EXCEPTION]:    at LegendaryClient.Logic.Region.Garena.VN.get_PingAddresses()
(03/04/2015 12:19 PM) [LOG]: The method or operation is not implemented.
(03/04/2015 12:19 PM) [LOG]: matching-queue-URF-5x5-game-queue
(03/04/2015 12:19 PM) [LOG]: matching-queue-URF-5x5-game-queue
(03/04/2015 12:19 PM) [LOG]: matching-queue-URF-BOT-5x5-game-queue
(03/04/2015 12:19 PM) [LOG]: matching-queue-URF-BOT-5x5-game-queue
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [EXCEPTION]: 
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [EXCEPTION]: 
(03/04/2015 12:19 PM) [LOG]: Items collection was most likely modified.
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [EXCEPTION]: 
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [EXCEPTION]: 
(03/04/2015 12:19 PM) [EXCEPTION]: A first chance exception was thrown
(03/04/2015 12:19 PM) [EXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [EXCEPTION]: 
(03/04/2015 12:19 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(03/04/2015 12:19 PM) [UNHANDLEDEXCEPTION]: com.riotgames.platform.messaging.UnexpectedServiceException : null
(03/04/2015 12:19 PM) [UNHANDLEDEXCEPTION]:
