### ISSUE TITLE
unable to get into Loginpage

### ISSUE THREAD

**Issue by voshond** [SightstoneOfficial/LegendaryClient#352]
been more available now so i wanted to look into some UI again. tried login into EUW but crashed. since then i cant even get into the loginpage.

``` csharp
(13/06/2015 17:09) [LOG]: LegendaryClient Started Up Successfully
(13/06/2015 17:09) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(13/06/2015 17:09) [EXCEPTION]: A first chance exception was thrown
(13/06/2015 17:09) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(13/06/2015 17:09) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(13/06/2015 17:09) [LOG]: Newest DataDragon Version: 5.11.1
(13/06/2015 17:09) [LOG]: Current DataDragon Version: 5.11.1
(13/06/2015 17:09) [LOG]: DDragon Version (LOL Version) = 5.11.1
(13/06/2015 17:09) [LOG]: Newest Air Assets Version: 0.0.1.148
(13/06/2015 17:09) [LOG]: Current Air Assets Version: 0.0.1.148
(13/06/2015 17:09) [LOG]: Checking Theme...
(13/06/2015 17:09) [LOG]: Trying to detect League of Legends GameClient
(13/06/2015 17:09) [LOG]: League of Legends is located at: Q:\Spiele\League of Legends\
(13/06/2015 17:09) [LOG]: Latest League of Legends GameClient: 0.0.1.92
(13/06/2015 17:09) [LOG]: Checking if League of Legends is Up-To-Date
(13/06/2015 17:09) [LOG]: League of Legends is Up-To-Date
(13/06/2015 17:09) [LOG]: LegendaryClient Has Finished Patching
(13/06/2015 17:09) [EXCEPTION]: A first chance exception was thrown
(13/06/2015 17:09) [EXCEPTION]: Index was outside the bounds of the array.
(13/06/2015 17:09) [EXCEPTION]:    at LegendaryClient.Windows.LoginPage..ctor()
(13/06/2015 17:09) [EXCEPTION]: A first chance exception was thrown
(13/06/2015 17:09) [EXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(13/06/2015 17:09) [EXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
(13/06/2015 17:09) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(13/06/2015 17:09) [EXCEPTION]: A first chance exception was thrown
(13/06/2015 17:09) [EXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(13/06/2015 17:09) [EXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Complete.MethodFactory.GetObjectCreatorExpressions(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 27
   at Complete.MethodFactory.CompileObjectConstructor(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 46
   at RtmpSharp.IO.SerializerObjectFactory.Register(Type type) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 53
   at RtmpSharp.IO.SerializerObjectFactory..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 26
   at RtmpSharp.IO.SerializationContext..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializationContext.cs:line 19
   at LegendaryClient.Logic.Riot.RiotCalls.RegisterObjects()
   at LegendaryClient.Windows.LoginPage.<LoginButton_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
(13/06/2015 17:09) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(13/06/2015 17:09) [UNHANDLEDEXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(13/06/2015 17:09) [UNHANDLEDEXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Complete.MethodFactory.GetObjectCreatorExpressions(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 27
   at Complete.MethodFactory.CompileObjectConstructor(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 46
   at RtmpSharp.IO.SerializerObjectFactory.Register(Type type) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 53
   at RtmpSharp.IO.SerializerObjectFactory..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 26
   at RtmpSharp.IO.SerializationContext..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializationContext.cs:line 19
   at LegendaryClient.Logic.Riot.RiotCalls.RegisterObjects()
   at LegendaryClient.Windows.LoginPage.<LoginButton_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()
```

**Comment by nairaner** [comment]
Maybe try rebuilding rtmp-sharp? This error just doesnt make sense

**Comment by voshond** [comment]
i did build the whole project new. nothing changed.
i deleted my configuration file in appdata/local and seem to get into the login page.

tho when i put in my stuff and hit login:

``` csharp
(14/06/2015 11:35) [LOG]: LegendaryClient Started Up Successfully
(14/06/2015 11:35) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(14/06/2015 11:35) [LOG]: Newest DataDragon Version: 5.11.1
(14/06/2015 11:35) [LOG]: Current DataDragon Version: 5.11.1
(14/06/2015 11:35) [LOG]: DDragon Version (LOL Version) = 5.11.1
(14/06/2015 11:35) [LOG]: Newest Air Assets Version: 0.0.1.148
(14/06/2015 11:35) [LOG]: Current Air Assets Version: 0.0.1.148
(14/06/2015 11:35) [LOG]: Checking Theme...
(14/06/2015 11:35) [LOG]: Trying to detect League of Legends GameClient
(14/06/2015 11:35) [LOG]: League of Legends is located at: Q:\Spiele\League of Legends\
(14/06/2015 11:35) [LOG]: Latest League of Legends GameClient: 0.0.1.92
(14/06/2015 11:35) [LOG]: Checking if League of Legends is Up-To-Date
(14/06/2015 11:35) [LOG]: League of Legends is Up-To-Date
(14/06/2015 11:35) [LOG]: LegendaryClient Has Finished Patching
(14/06/2015 11:35) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(14/06/2015 11:35) [EXCEPTION]: A first chance exception was thrown
(14/06/2015 11:35) [EXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(14/06/2015 11:35) [EXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
(14/06/2015 11:35) [EXCEPTION]: A first chance exception was thrown
(14/06/2015 11:35) [EXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(14/06/2015 11:35) [EXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Complete.MethodFactory.GetObjectCreatorExpressions(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 27
   at Complete.MethodFactory.CompileObjectConstructor(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 46
   at RtmpSharp.IO.SerializerObjectFactory.Register(Type type) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 53
   at RtmpSharp.IO.SerializerObjectFactory..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 26
   at RtmpSharp.IO.SerializationContext..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializationContext.cs:line 19
   at LegendaryClient.Logic.Riot.RiotCalls.RegisterObjects()
   at LegendaryClient.Windows.LoginPage.<LoginButton_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
(14/06/2015 11:35) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(14/06/2015 11:35) [UNHANDLEDEXCEPTION]: Type Complete.Threading.TaskCallbackManager`2+<>c[K,V] is a generic type definition
(14/06/2015 11:35) [UNHANDLEDEXCEPTION]:    at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at Complete.MethodFactory.GetObjectCreatorExpressions(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 27
   at Complete.MethodFactory.CompileObjectConstructor(ConstructorInfo constructor) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\Complete\MethodFactory.cs:line 46
   at RtmpSharp.IO.SerializerObjectFactory.Register(Type type) in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 53
   at RtmpSharp.IO.SerializerObjectFactory..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializerObjectFactory.cs:line 26
   at RtmpSharp.IO.SerializationContext..ctor() in C:\Users\Martin\Source\GitHub\LegendaryClient\rtmp-sharp\IO\SerializationContext.cs:line 19
   at LegendaryClient.Logic.Riot.RiotCalls.RegisterObjects()
   at LegendaryClient.Windows.LoginPage.<LoginButton_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()
```

**Comment by nairaner** [comment]
can you check if compiled version from appveyor works?

**Comment by voshond** [comment]
odd that this is working. what can i do?

**Comment by newchild** [comment]
Getting the same error when compiling on my Visual Studio 2015, I am using the german system language

**Comment by nairaner** [comment]
@mhn23 Do you also use VS2015?

**Comment by voshond** [comment]
seems fixed via vs 2013.
