### ISSUE TITLE
Get stuck at login

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#360]
Get stuck at login (Garena TW)
Log : 

```
(6/15/2015 6:01 PM) [LOG]: LegendaryClient Started Up Successfully
(6/15/2015 6:01 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(6/15/2015 6:01 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(6/15/2015 6:01 PM) [LOG]: Newest DataDragon Version: 5.11.1
(6/15/2015 6:01 PM) [LOG]: Current DataDragon Version: 5.11.1
(6/15/2015 6:01 PM) [LOG]: DDragon Version (LOL Version) = 5.11.1
(6/15/2015 6:01 PM) [LOG]: Newest Air Assets Version: 0.0.1.148
(6/15/2015 6:01 PM) [LOG]: Current Air Assets Version: 0.0.1.148
(6/15/2015 6:01 PM) [LOG]: Checking Theme...
(6/15/2015 6:01 PM) [LOG]: Trying to detect League of Legends GameClient
(6/15/2015 6:01 PM) [LOG]: League of Legends is located at: C:\GarenaLoLTW\GameData\Apps\LoLTW\
(6/15/2015 6:01 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.92
(6/15/2015 6:01 PM) [LOG]: Checking if League of Legends is Up-To-Date
(6/15/2015 6:01 PM) [LOG]: League of Legends is Up-To-Date
(6/15/2015 6:01 PM) [LOG]: LegendaryClient Has Finished Patching
(6/15/2015 6:01 PM) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(6/15/2015 6:01 PM) [LOG]: Received token, it is: ma1ACV+S4kHLkqWoj/1AomdxyEayl0hVDwZILHgiQ5k21+qINvuC0EO4k31a1XJrgWiZgaXNXSZpcjXX1xfxn6wXXbyeJ8jP4MOcsIsHNFmL7U/ajg5XIKzBRlyTBbzC6nur/ZCCv5j4ahwfRN6JWuObA807Q+/PSYHSgoB5Jbl2RYFxJbhCQkWvSN1PR+vkaugihq4w/8bf3QPbgFGY+yVXByhYs95QzxyrNIZtaBtyaYyo2IQDSC+L/20L3SzImQN4vDBivfCME0LWfP9d25pKGW2zHPMZ57VhfhllpfkOoQfRoD08CHslVTH42vDS23biY3jrA/yZbNYPjsSRFA==
(6/15/2015 6:01 PM) [LOG]: rate+|+80
(6/15/2015 6:01 PM) [LOG]: token+|+3vgxlv5DV53a6r7eKSwHVyRlnrVV6r5VSgAuU7nTlTuaRrw-VHzr9oPLukhtGHwQL7ayQ-Q2xl4mwd+a3xTY6w==
(6/15/2015 6:01 PM) [LOG]: reason+|+login_rate
(6/15/2015 6:01 PM) [LOG]: status+|+LOGIN
(6/15/2015 6:01 PM) [LOG]: delay+|+5000
(6/15/2015 6:01 PM) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(6/15/2015 6:01 PM) [LOG]: user+|+163463679
(6/15/2015 6:01 PM) [LOG]: gasToken+|+{
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "163463679",
  "signature": "ELuI12UdS8bk17fzmruVlk4coaO3Ya2HDkt/BqPL8NyEN02xV/G85Y/ratUwXJ6BiZA8inIaS29CUlSBa0WxYPi6V/bEXO6cMMU6YEzzk8EKL1spgPMLLegWzpyKgs8FoTyArY62inRv0iIe2kmg3hOFvuKEqbGA3cVxiYzbzBx4SQMZt3bG6Uh9H9CYSIphBB11M83QQEdeEiD7159qSbdeHQ+k0G2Bvvc72DRmpIDGEzAMCyvRu+4/3mEZVwofVshKdnKv/3AEfMMOkkCuPE7HumXpcwEroKV5A3v2YjMMJt5NedIBna9ehJVH7DDiIAgg98+XHboZ3AdB0De+OA==",
  "summoner_name": null,
  "date_time": 1434362526998,
  "pvpnet_account_id": 163463679
}
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: Value was either too large or too small for an Int32.
(6/15/2015 6:01 PM) [EXCEPTION]:    at System.Convert.ToInt32(Double value)
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: Thread was being aborted.
(6/15/2015 6:01 PM) [EXCEPTION]:    at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: Thread was being aborted.
(6/15/2015 6:01 PM) [EXCEPTION]: Thread was being aborted.
(6/15/2015 6:01 PM) [EXCEPTION]:    at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
(6/15/2015 6:01 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketReader.ReadLoop() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpPacketReader.cs:line 104
(6/15/2015 6:01 PM) [EXCEPTION]: A first chance exception was thrown
(6/15/2015 6:01 PM) [EXCEPTION]: Thread was being aborted.
(6/15/2015 6:01 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketWriter.WriteLoop() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpPacketWriter.cs:line 77
```

**Comment by NitroXenon** [comment]
If I comment out :
LoginPage.xaml.cs Line 461

```
Client.PlayerChampions = await RiotCalls.GetAvailableChampions();
```

I can login...

**Comment by nairaner** [comment]
You have working LoLNotes right? Can you check what did they change?

**Comment by NitroXenon** [comment]
Oh yea I almost forgot LoLNotes
I'll check it later

**Comment by NitroXenon** [comment]
I've use LoLNotes to check. Nothing is changed...

**Comment by secretdataz** [comment]
It may have something to do with chinese characters,

**Comment by nairaner** [comment]
@NitroXenon can you turn on "Break on all exception" and check where the int error is thrown?

**Comment by NitroXenon** [comment]
I need to sleep now. Maybe test it tmr.

**Comment by nairaner** [comment]
According to ##loldev gameIds reached int32 cap, so that might be the problem

**Comment by NitroXenon** [comment]
![exception4](https://cloud.githubusercontent.com/assets/7702985/8267326/cdffc1a2-178e-11e5-9dd2-89fb3a1af210.jpg)

**Comment by NitroXenon** [comment]
The value is 1427631984000.0 
The targetType is Int32

**Comment by NitroXenon** [comment]
So I rewrote the ConvertObject  method to the following for testing :
```
        static object ConvertObject(Type sourceType, Type targetType, object value)
        {
            var converter = TypeDescriptor.GetConverter(sourceType);
            if (converter.CanConvertTo(targetType))
            {
                if (targetType.Name == "Int32")
                {
                    object result = null;
                    try
                    {
                        result = converter.ConvertTo(null, CultureInfo.InvariantCulture, value, targetType);
                    }
                    catch (System.OverflowException) 
                    {
                        result = converter.ConvertTo(null, CultureInfo.InvariantCulture, value, typeof(Int64));
                    }
                    return result;
                }
                return converter.ConvertTo(null, CultureInfo.InvariantCulture, value, targetType);
            }

            return Convert.ChangeType(value, targetType, CultureInfo.InvariantCulture);
        }
```

After that, I got another the OverflowException again...
![exception5](https://cloud.githubusercontent.com/assets/7702985/8267347/ab69b21e-178f-11e5-9d7f-a2dfe6d1b61e.jpg)

The instance is {LegendaryClient.Logic.Riot.Platform.ChampionDTO}
The value is 1427631984000

**Comment by NitroXenon** [comment]
WTF? My smurf account of can login while my main account got the exception. What???
