### ISSUE TITLE
champselect crash nullpointer

### ISSUE THREAD

**Issue by voshond** [SightstoneOfficial/LegendaryClient#368]
``` csharp
(16/06/2015 10:41) [LOG]: LegendaryClient Started Up Successfully
(16/06/2015 10:41) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(16/06/2015 10:41) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:41) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(16/06/2015 10:41) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(16/06/2015 10:41) [LOG]: Checking Plugin dependencies...
(16/06/2015 10:41) [LOG]: Plugin dependencies are installed
(16/06/2015 10:41) [LOG]: Newest DataDragon Version: 5.11.1
(16/06/2015 10:41) [LOG]: Current DataDragon Version: 5.11.1
(16/06/2015 10:41) [LOG]: DDragon Version (LOL Version) = 5.11.1
(16/06/2015 10:41) [LOG]: Newest Air Assets Version: 0.0.1.148
(16/06/2015 10:41) [LOG]: Current Air Assets Version: 0.0.1.148
(16/06/2015 10:41) [LOG]: Checking Theme...
(16/06/2015 10:41) [LOG]: Trying to detect League of Legends GameClient
(16/06/2015 10:41) [LOG]: League of Legends is located at: Q:\Spiele\League of Legends\
(16/06/2015 10:41) [LOG]: Latest League of Legends GameClient: 0.0.1.92
(16/06/2015 10:41) [LOG]: Checking if League of Legends is Up-To-Date
(16/06/2015 10:41) [LOG]: League of Legends is Up-To-Date
(16/06/2015 10:41) [LOG]: LegendaryClient Has Finished Patching
(16/06/2015 10:42) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(16/06/2015 10:42) [LOG]: rate+|+110
(16/06/2015 10:42) [LOG]: token+|+pl-2i+JEoL-h1RBDhaoj17I6lIH3PuDYX-hPEOEHc5ZPhjPKprg48ewBnscz2m1eUTTMuMKNStFY4jRKK3Wf3g==
(16/06/2015 10:42) [LOG]: reason+|+login_rate
(16/06/2015 10:42) [LOG]: status+|+LOGIN
(16/06/2015 10:42) [LOG]: delay+|+5000
(16/06/2015 10:42) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(16/06/2015 10:42) [LOG]: user+|+mhn23
(16/06/2015 10:42) [LOG]: idToken+|+eyJhbGciOiJSUzI1NiJ9.eyJsb2wiOlt7InVpZCI6MjYzODQ4NzYsImN1aWQiOjI2Mzg0ODc2LCJ1bmFtZSI6Im1objIzIiwiY3BpZCI6IkVVVzEiLCJwaWQiOiJFVVcxIn1dLCJleHAiOjE0MzQ1MzA1MjUsInN1YiI6InVybjpyaW90OnBpZDp2MTpNall6T0RRNE56WTZSVlZYTVEiLCJ0YWciOltdLCJhdWQiOiJsb2wiLCJpc3MiOiJodHRwczpcL1wvZ2FzLnJpb3RnYW1lcy5jb20iLCJpYXQiOjE0MzQ0NDQxMjUsImFtciI6ImNsaWVudF9iYXNpYyJ9.dC-W54gky_DNt88NnTT3hCgra-98uWX7u2HYL39vMR0GLJXQYOklKe8HuR-9yYhfFLwypNZGAp3q37wQ7b9NQs7em4YqMQWCtKXSSIx_4jtlJgmMQNmbWaCykoJbdIFv_eFNEvivsGnbSDjIoBkTuQaPAFTCgZNIjFTMn6jx9M5Ku924zQgnGzy02gS-vFdXivz_oPwv5Nphb3yr9PrXmnqIGBGkrrTPiTKw7VXsX0oAz3GSxtR6GjV2d4yPYfuR4qLr4UYy01o7bysqiHeJ_I2UMeObHpwOGfxnd4aJGBF95mfA6oon4ZWmh0L8hRMJZSALhnFnbj3oIEZDeX9NQg
(16/06/2015 10:42) [LOG]: gasToken+|+{
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "26384876",
  "signature": "eOKJ8vHep/wQEIXPzNNXpcbhw/XeaHgHduz4JNGbCzUSKVwwMc6dBti1CS46DjwFPCTBNRUfuqjntb0OAJd/ymGO1IDWfgMAbikyh0b3gFnRgHKsgA3mHgGUqugADLV2YYgoo/Mm8P09NETN9GKhDaiOC7deVq+LBMQWsJ9c/OaRTgZilyJWRZ2Rv/LwKrUgbpiZ1hukyveVf0j7Rtk1nE0mDtoEklUkY61n7QdEw1d0DpJFZ8mPx5YkyOibyJG0kelJVkzBUeL2kPqZuPGYRsZCPZF0s5OgZPl5oWlswwBXNzWt2xOxYFWsN4aeRhKbjKyIVVd01koZw+3tZ+BhZw==",
  "summoner_name": null,
  "date_time": 1434444125226,
  "pvpnet_account_id": 26384876
}
(16/06/2015 10:42) [LOG]: Connected to EUW and logged in as mhn23
(16/06/2015 10:42) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(16/06/2015 10:42) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:42) [EXCEPTION]: Application identity is not set.
(16/06/2015 10:42) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(16/06/2015 10:42) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:42) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(16/06/2015 10:42) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(16/06/2015 10:42) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(16/06/2015 10:42) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(16/06/2015 10:42) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:42) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(16/06/2015 10:42) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/EUW1/-2147483648/26384876?tab=overview
(16/06/2015 10:42) [LOG]: Switching to the page: LegendaryClient.Windows.SettingsPage
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(16/06/2015 10:43) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(16/06/2015 10:43) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(16/06/2015 10:43) [LOG]: Switching to the page: LegendaryClient.Windows.ReplayPage
(16/06/2015 10:43) [LOG]: Switching to the page: LegendaryClient.Windows.SettingsPage
(16/06/2015 10:43) [LOG]: Switching to the page: LegendaryClient.Windows.PlayPage
(16/06/2015 10:43) [LOG]: Now in Queue
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: 0
(16/06/2015 10:43) [LOG]: 0
(16/06/2015 10:43) [LOG]: 0
(16/06/2015 10:43) [LOG]: 0
(16/06/2015 10:43) [LOG]: 0
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(16/06/2015 10:43) [LOG]: Switching to the page: LegendaryClient.Windows.ChampSelectPage
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: Object reference not set to an instance of an object.
(16/06/2015 10:43) [EXCEPTION]:    at LegendaryClient.Logic.Client.ChatClient_OnMessage(Object sender, Message msg)
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: Unexpected exception
(16/06/2015 10:43) [EXCEPTION]:    at jabber.protocol.AsynchElementStream.Push(Byte[] buf, Int32 offset, Int32 length)
(16/06/2015 10:43) [LOG]: Error with chat connection
(16/06/2015 10:43) [EXCEPTION]: A first chance exception was thrown
(16/06/2015 10:43) [EXCEPTION]: Object reference not set to an instance of an object.
(16/06/2015 10:43) [EXCEPTION]:    at jabber.connection.XmppStream.SendNewStreamHeader()
(16/06/2015 10:43) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(16/06/2015 10:43) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(16/06/2015 10:43) [UNHANDLEDEXCEPTION]:    at jabber.connection.XmppStream.SendNewStreamHeader()
   at jabber.connection.XmppStream.jabber.connection.IStanzaEventListener.Connected()
   at jabber.connection.SocketStanzaStream.bedrock.net.ISocketEventListener.OnConnect(BaseSocket sock)
   at bedrock.net.AsyncSocket.ExecuteConnect(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by voshond** [comment]
guess was fixed with the EUW gameID int64 stuff
