### ISSUE TITLE
NA login crash

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#375]
Logs  :

```
(6/18/2015 9:23 PM) [LOG]: LegendaryClient Started Up Successfully
(6/18/2015 9:23 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(6/18/2015 9:23 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:23 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(6/18/2015 9:23 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(6/18/2015 9:23 PM) [LOG]: Checking Plugin dependencies...
(6/18/2015 9:24 PM) [LOG]: Plugin dependencies are installed
(6/18/2015 9:24 PM) [LOG]: Newest DataDragon Version: 5.11.1
(6/18/2015 9:24 PM) [LOG]: Current DataDragon Version: 5.11.1
(6/18/2015 9:24 PM) [LOG]: DDragon Version (LOL Version) = 5.11.1
(6/18/2015 9:24 PM) [LOG]: Newest Air Assets Version: 0.0.1.148
(6/18/2015 9:24 PM) [LOG]: Current Air Assets Version: 0.0.1.148
(6/18/2015 9:24 PM) [LOG]: Checking Theme...
(6/18/2015 9:24 PM) [LOG]: Trying to detect League of Legends GameClient
(6/18/2015 9:24 PM) [LOG]: League of Legends is located at: C:\GarenaLoLTW\GameData\Apps\LoLTW\lol.exe
(6/18/2015 9:24 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.93
(6/18/2015 9:24 PM) [LOG]: Checking if League of Legends is Up-To-Date
(6/18/2015 9:24 PM) [LOG]: League of Legends is not Up-To-Date. Please Update League Of Legends
(6/18/2015 9:24 PM) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(6/18/2015 9:24 PM) [LOG]: rate+|+150
(6/18/2015 9:24 PM) [LOG]: token+|+NTMkoVDwUV4PCtse00Syd3r0m98i7z47s7mtgSUa4PboC0j+6kQTStIcZ1wgz5Neg1+DkVwZmfVoaInilNYKcA==
(6/18/2015 9:24 PM) [LOG]: reason+|+login_rate
(6/18/2015 9:24 PM) [LOG]: status+|+LOGIN
(6/18/2015 9:24 PM) [LOG]: delay+|+5000
(6/18/2015 9:24 PM) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(6/18/2015 9:24 PM) [LOG]: user+|+peter9104
(6/18/2015 9:24 PM) [LOG]: idToken+|+eyJhbGciOiJSUzI1NiJ9.eyJsb2wiOlt7InVpZCI6MjAyOTkxNjUzLCJjdWlkIjoyMDI5OTE2NTMsInVuYW1lIjoicGV0ZXI5MTA0IiwiY3BpZCI6Ik5BMSIsInBpZCI6Ik5BMSJ9XSwiZXhwIjoxNDM0NzIwMjc4LCJzdWIiOiJ1cm46cmlvdDpwaWQ6djE6TWpBeU9Ua3hOalV6T2s1Qk1RIiwidGFnIjpbXSwiYXVkIjoibG9sIiwiaXNzIjoiaHR0cHM6XC9cL2dhcy5yaW90Z2FtZXMuY29tIiwiaWF0IjoxNDM0NjMzODc4LCJhbXIiOiJjbGllbnRfYmFzaWMifQ.a2nZHPldEOsz_h1OvI0ZAHllBS-CmiGBdSJpqHgxoL81RmWVSiTuIgkxYZptgJkFAQkxeCQJPTI5tK5mqGrA_q4Qlbl55G6lEVUoFGxRJ6ivz8Db6KXEbL0HEIiw3ZWiLzOQbXqbzsJO1UAvji79UVWiLOyMAaGXIP4tHPOIB2mH-KsNiOTqZVXLy563JNZ8z9EpDjwGVocC1l9LxX4jX9Gazl-254uI_0eI9z_jzx-8DSRIl3KMJiYp9-_UBSbWvZdGhgCi3IbM4TTxm6P5LeJJY8lMI0BTIIxnYKRsDDl4OepRHt7qmLRhuQSfEYcOmXOp3bJkcpCFUv0wkSrdqQ
(6/18/2015 9:24 PM) [LOG]: gasToken+|+{
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "202991653",
  "signature": "rBbLa0kHEo7C9w08m8Lk2DoZfZ6org++SCVA9m/Z2BG+fLcjkJ10HXjMK07d+AzS5RtdUqysrhLFpjnGq6Ei2RkCjY54GnHaBU5oT6axMDWVsgiC/U6S9QKX4LKWNH7mS294IK0edmATZUuJguz9efDi2FThBy5sFjzSel+ALxbvwYDGDTOdzLBNOPhhDqP0Gx5rC/8nR+is0CDyMwUJs2jLcE/DkrTw1ClRdC5tWEzCr9yeARV7gAXVCja/XWL68tPU9ewt2YIO2i1frR679xV5TT8PHO8XBOANvrEh4MLRelvPh31ic2Dc2zSXnQ4V+9QC7uaxaW8IBg3FpB4+AA==",
  "summoner_name": null,
  "date_time": 1434633878125,
  "pvpnet_account_id": 202991653
}
(6/18/2015 9:24 PM) [LOG]: Auto login
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: An existing connection was forcibly closed by the remote host
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
   at RtmpSharp.Net.RtmpClient.<GetRtmpStreamAsync>d__2a.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
   at RtmpSharp.Net.RtmpClient.<GetRtmpStreamAsync>d__2a.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<ConnectAsync>d__8.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(6/18/2015 9:24 PM) [EXCEPTION]: A first chance exception was thrown
(6/18/2015 9:24 PM) [EXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [EXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
   at RtmpSharp.Net.RtmpClient.<GetRtmpStreamAsync>d__2a.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<ConnectAsync>d__8.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LegendaryClient.Windows.LoginPage.<Login>d__17.MoveNext() in c:\git\LegendaryClient\LegendaryClient\Windows\LoginPage.xaml.cs:line 414
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(6/18/2015 9:24 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(6/18/2015 9:24 PM) [UNHANDLEDEXCEPTION]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
(6/18/2015 9:24 PM) [UNHANDLEDEXCEPTION]:    at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1](Func`4 beginMethod, Action`1 endMethod, TArg1 arg1, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost)
   at RtmpSharp.Net.RtmpClient.<GetRtmpStreamAsync>d__2a.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RtmpSharp.Net.RtmpClient.<ConnectAsync>d__8.MoveNext() in c:\git\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at LegendaryClient.Windows.LoginPage.<Login>d__17.MoveNext() in c:\git\LegendaryClient\LegendaryClient\Windows\LoginPage.xaml.cs:line 414
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LegendaryClient.App.Main() in c:\git\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by NitroXenon** [comment]
I've tried to login for 3 times. The first 2 times got the above exception. The third time got success.

**Comment by NitroXenon** [comment]
50% chance getting this exception and crash when I login to NA :(

**Comment by eddy5641** [comment]
This is with ssl

**Comment by eddy5641** [comment]
Should not tell you that there was a problem with ssl. Just try to log in again
