### ISSUE TITLE
Multi user

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#392]
Yep we are adding this
I don't think I can get a server anytime soon so they will be local
Users will be stored locally and can be exported into a .lcuser file

Note i will be making a lot of changes to client.cs
Do you want me to prepare for it than implement after the ui is done

**Comment by voshond** [comment]
you can use the material-design branch and start working, just add the stuff you have or use gitter in case you need stuff to be happening.

bridging too?

**Comment by secretdataz** [comment]
@mhn23 No, you guys should fork from material design branch not work in it.

**Comment by voshond** [comment]
why not? i think adding all this will take it's time to be actually usable so it wouldnt fuck up everything

**Comment by secretdataz** [comment]
All big feature should be worked from their respective branch to prevent fuck ups.

**Comment by eddy5641** [comment]
I typed User and UserClient.calls too many times getting it to work. Now just a little more work then you can select other non live servers and have it save read and login.

**Comment by voshond** [comment]
but right now its just login right? bridging isnt implemented? but so far i wait until the most stuff is done and will working mroe on the UI with you.

**Comment by eddy5641** [comment]
Everything is implemented except the crypto stuff needs to be fixed
Borrowing stuff from legacy pvp because it works

**Comment by voshond** [comment]
@eddy5641
seems like in the final steps,
as soon as i'm able to test in runtime again i will do more UI stuff
i monitor the process hourly and will do more asap

**Comment by eddy5641** [comment]
managed to get it to work. Now fix up chat and done

**Comment by voshond** [comment]
i just woke up and looked into it.
LCUser File may need Region Label too for filename,
have an account on NA and EUW with the same name, seem to causing issues.

**Comment by eddy5641** [comment]
I will fix this after I can manage to build a new comp. Using a phone isn't the best idea

**Comment by voshond** [comment]
oh what happend to your old one

**Comment by eddy5641** [comment]
It won't turn on. Its an old comp though and had thermal problems so CPU prob died early

**Comment by eddy5641** [comment]
Where is /cry when you need it

**Comment by voshond** [comment]
oh shit, if you need help building one, or anything i did that for a job about 4 years after i finished my Networking Apprenticeship. (thats why i have a noctua cooler)

**Comment by voshond** [comment]
```
(17/07/2015 13:01) [LOG]: LegendaryClient Started Up Successfully
(17/07/2015 13:01) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(17/07/2015 13:01) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:01) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(17/07/2015 13:01) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(17/07/2015 13:01) [LOG]: Checking Plugin dependencies...
(17/07/2015 13:01) [LOG]: Plugin dependencies are installed
(17/07/2015 13:01) [LOG]: Newest DataDragon Version: 5.13.1
(17/07/2015 13:01) [LOG]: Current DataDragon Version: 5.13.1
(17/07/2015 13:01) [LOG]: DDragon Version (LOL Version) = 5.13.1
(17/07/2015 13:01) [LOG]: Newest Air Assets Version: 0.0.1.151
(17/07/2015 13:01) [LOG]: Current Air Assets Version: 0.0.1.151
(17/07/2015 13:01) [LOG]: Checking Theme...
(17/07/2015 13:01) [LOG]: Trying to detect League of Legends GameClient
(17/07/2015 13:01) [LOG]: League of Legends is located at: Q:\Spiele\League of Legends\
(17/07/2015 13:01) [LOG]: Latest League of Legends GameClient: 0.0.1.95
(17/07/2015 13:01) [LOG]: Checking if League of Legends is Up-To-Date
(17/07/2015 13:01) [LOG]: League of Legends is Up-To-Date
(17/07/2015 13:01) [LOG]: LegendaryClient Has Finished Patching
(17/07/2015 13:01) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(17/07/2015 13:02) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:02) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(17/07/2015 13:02) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(17/07/2015 13:02) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:02) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(17/07/2015 13:02) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(17/07/2015 13:02) [LOG]: rate+|+0
(17/07/2015 13:02) [LOG]: reason+|+invalid_credentials
(17/07/2015 13:02) [LOG]: status+|+FAILED
(17/07/2015 13:02) [LOG]: delay+|+5000
(17/07/2015 13:02) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:02) [EXCEPTION]: Object reference not set to an instance of an object.
(17/07/2015 13:02) [EXCEPTION]:    at LegendaryClient.Logic.Riot.RiotCalls.<GetRestToken>d__27.MoveNext()
(17/07/2015 13:02) [LOG]: Login Failure: Object reference not set to an instance of an object.
(17/07/2015 13:02) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:02) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(17/07/2015 13:02) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(17/07/2015 13:02) [EXCEPTION]: A first chance exception was thrown
(17/07/2015 13:02) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(17/07/2015 13:02) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
```

this happens when i use the normal login as single user

**Comment by voshond** [comment]
```
[Exception] The given key was not present in the dictionary.
[Exception] Exception has been thrown by the target of an invocation.
[UnhandledException] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LegendaryClient.Windows.LoginPage.<>c__DisplayClass46.<GotLoginPacket>b__40() in q:\Privat\Projekte\Github\LegendaryClient\LegendaryClient\Windows\LoginPage.xaml.cs:line 687
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LegendaryClient.App.Main() in q:\Privat\Projekte\Github\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
LegendaryClient has closed and the pipe has been shut down!
This window will now close in 30 seconds, do "-abortShutdown" to stop the shutdown
```

when adding a user

**Comment by eddy5641** [comment]
Screwed up atm but will fix in a bit

**Comment by eddy5641** [comment]
It only finds 3 accounts for me but here:
![lclogin](https://cloud.githubusercontent.com/assets/6468338/8818146/60df88c4-2ff2-11e5-86a2-f5dc5753a2eb.PNG)
