### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by heIlo** [SightstoneOfficial/LegendaryClient#397]
the client crashes on launch :/

(9/7/2015 11:57 PM) [LOG]: LegendaryClient Started Up Successfully
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 109.163.228.98:443
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
(9/7/2015 11:57 PM) [EXCEPTION]: A first chance exception was thrown
(9/7/2015 11:57 PM) [EXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at LegendaryClient.Windows.PatcherPage.<StartPatcher>d__c.MoveNext() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\PatcherPage.xaml.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(9/7/2015 11:57 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(9/7/2015 11:57 PM) [UNHANDLEDEXCEPTION]: Unable to connect to the remote server
(9/7/2015 11:57 PM) [UNHANDLEDEXCEPTION]:    at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at LegendaryClient.Windows.PatcherPage.<StartPatcher>d__c.MoveNext() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\PatcherPage.xaml.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0

**Comment by eddy5641** [comment]
Internet lag (ours riots or your). The other crash is from the new champ

**Comment by secretdataz** [comment]
We should add something to make it gracefully exit instead of crashing.

**Comment by eddy5641** [comment]
prob have the lclogger kill lc if it detects the crash and show a win to ask the user if they want to restart

**Comment by secretdataz** [comment]
Alright, that should be another issue. Closing this.
