### ISSUE TITLE
Ranked champ select crash

### ISSUE THREAD

**Issue by ar1a** [SightstoneOfficial/LegendaryClient#402]
(7/14/2015 2:36 PM) [LOG]: Connected to OCE and logged in as Blackstab1337
(7/14/2015 2:36 PM) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Application identity is not set.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.ChunkParser.CompletePayloadReadOperation(Int32 bytesRead)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.ChunkParser.CompletePayloadReadOperation(Int32 bytesRead)
   at System.Net.ChunkParser.HandlePayload()
   at System.Net.ChunkParser.ProcessResponse()
   at System.Net.ChunkParser.Read(Byte[] userBuffer, Int32 userBufferOffset, Int32 userBufferCount)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at MS.Internal.WpfWebRequestHelper.EndGetResponse(WebRequest request, IAsyncResult ar)
   at System.Net.ConnectStream.ReadWithoutValidation(Byte[] buffer, Int32 offset, Int32 size, Boolean abortOnError)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: The request was aborted: The connection was closed unexpectedly.
(7/14/2015 2:36 PM) [EXCEPTION]:    at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanEndTag(Byte[] buf, Int32 off, Int32 end, Token token)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanLt(Byte[] buf, Int32 off, Int32 end, ContentToken token)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(7/14/2015 2:36 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:36 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(7/14/2015 2:36 PM) [EXCEPTION]:    at xpnet.Encoding.scanLt(Byte[] buf, Int32 off, Int32 end, ContentToken token)
(7/14/2015 2:36 PM) [LOG]: URF
(7/14/2015 2:36 PM) [LOG]: URF
(7/14/2015 2:36 PM) [LOG]: URF
(7/14/2015 2:36 PM) [LOG]: URF
(7/14/2015 2:36 PM) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/OC1/96751333/200125090?tab=overview
(7/14/2015 2:37 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PlayPage
(7/14/2015 2:37 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:37 PM) [EXCEPTION]: The method or operation is not implemented.
(7/14/2015 2:37 PM) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses()
(7/14/2015 2:37 PM) [LOG]: The method or operation is not implemented.
(7/14/2015 2:37 PM) [LOG]: Switching to the page: LegendaryClient.Windows.CreateCustomGamePage
(7/14/2015 2:37 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.LobbyStatus
(7/14/2015 2:37 PM) [LOG]: Switching to the page: LegendaryClient.Windows.CustomGameLobbyPage
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:38 PM) [LOG]: Switching to the page: LegendaryClient.Windows.ChampSelectPage
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:38 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PluginsPage
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:38 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.PlayerCredentialsDto
(7/14/2015 2:38 PM) [LOG]: Switching to the page: LegendaryClient.Windows.InGame
(7/14/2015 2:38 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:38 PM) [EXCEPTION]: Attempted to divide by zero.
(7/14/2015 2:38 PM) [EXCEPTION]:    at LegendaryClient.GameScouter.<LoadPar>d__11.MoveNext()
(7/14/2015 2:38 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:38 PM) [EXCEPTION]: The given key was not present in the dictionary.
(7/14/2015 2:38 PM) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(7/14/2015 2:39 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 2:39 PM) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(7/14/2015 2:39 PM) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(7/14/2015 3:42 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PlayPage
(7/14/2015 3:42 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:42 PM) [EXCEPTION]: The method or operation is not implemented.
(7/14/2015 3:42 PM) [EXCEPTION]:    at LegendaryClient.Logic.Region.OCE.get_PingAddresses()
(7/14/2015 3:42 PM) [LOG]: The method or operation is not implemented.
(7/14/2015 3:42 PM) [LOG]: Now in Queue
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: 0
(7/14/2015 3:43 PM) [LOG]: 0
(7/14/2015 3:43 PM) [LOG]: 0
(7/14/2015 3:43 PM) [LOG]: 0
(7/14/2015 3:43 PM) [LOG]: 0
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Message received! The type is: LegendaryClient.Logic.Riot.Platform.GameDTO
(7/14/2015 3:43 PM) [LOG]: Switching to the page: LegendaryClient.Windows.ChampSelectPage
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: A call to SSPI failed, see inner exception.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: A call to SSPI failed, see inner exception.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: A call to SSPI failed, see inner exception.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: A call to SSPI failed, see inner exception.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: Safe handle has been closed
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.Net.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding_SECURITY(SafeDeleteContext phContext, ContextAttribute contextAttribute, Bindings\* buffer, SafeFreeContextBufferChannelBinding refHandle)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: The request was aborted: Could not create SSL/TLS secure channel.
(7/14/2015 3:43 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: Unexpected exception
(7/14/2015 3:43 PM) [EXCEPTION]:    at jabber.protocol.AsynchElementStream.Push(Byte[] buf, Int32 offset, Int32 length)
(7/14/2015 3:43 PM) [LOG]: Error with chat connection
(7/14/2015 3:43 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 3:43 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(7/14/2015 3:43 PM) [EXCEPTION]:    at jabber.connection.XmppStream.SendNewStreamHeader()
(7/14/2015 3:43 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(7/14/2015 3:43 PM) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(7/14/2015 3:43 PM) [UNHANDLEDEXCEPTION]:    at jabber.connection.XmppStream.SendNewStreamHeader()
   at jabber.connection.XmppStream.jabber.connection.IStanzaEventListener.Connected()
   at jabber.connection.SocketStanzaStream.bedrock.net.ISocketEventListener.OnConnect(BaseSocket sock)
   at bedrock.net.AsyncSocket.ExecuteConnect(IAsyncResult ar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* pOVERLAP)

crashed about 20 seconds in, possibly when they banned someone

**Comment by ghost** [comment]
This happens to me too. First sesion was just fine though.

**Comment by ar1a** [comment]
lost me lp :(

**Comment by newchild** [comment]
Don't play ranked with it.
Always remember:

"You can get the in-development bleeding edge builds from the link below. These builds are provided as-is and it might break, burn your computer or drag you down in elohell. We aren't responsible for whatever happens to your account or even your home-sweet-home. Use these builds at your risk."
Has todo with the chat, not the bans, @eddy5641

**Comment by ar1a** [comment]
I don't care about that, I'm reporting a bug.
