### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#410]
Invalid login crash
Server : NA

```
(7/25/2015 4:31 PM) [LOG]: Sightstone Started Up Successfully
(7/25/2015 4:31 PM) [LOG]: Switching to the page: Sightstone.Windows.PatcherPage
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(7/25/2015 4:31 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(7/25/2015 4:31 PM) [LOG]: Checking Plugin dependencies...
(7/25/2015 4:31 PM) [LOG]: Plugin dependencies are installed
(7/25/2015 4:31 PM) [LOG]: Newest DataDragon Version: 5.14.1
(7/25/2015 4:31 PM) [LOG]: Current DataDragon Version: 5.14.1
(7/25/2015 4:31 PM) [LOG]: DDragon Version (LOL Version) = 5.14.1
(7/25/2015 4:31 PM) [LOG]: Newest Air Assets Version: 0.0.1.152
(7/25/2015 4:31 PM) [LOG]: Current Air Assets Version: 0.0.1.152
(7/25/2015 4:31 PM) [LOG]: Checking Theme...
(7/25/2015 4:31 PM) [LOG]: Trying to detect League of Legends GameClient
(7/25/2015 4:31 PM) [LOG]: League of Legends is located at: C:\GarenaLoLTW\GameData\Apps\LoLTW\
(7/25/2015 4:31 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.97
(7/25/2015 4:31 PM) [LOG]: Checking if League of Legends is Up-To-Date
(7/25/2015 4:31 PM) [LOG]: League of Legends is Up-To-Date
(7/25/2015 4:31 PM) [LOG]: Sightstone Has Finished Patching
(7/25/2015 4:31 PM) [LOG]: Switching to the page: Sightstone.Windows.LoginPage
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(7/25/2015 4:31 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: The remote server returned an error: (403) Forbidden.
(7/25/2015 4:31 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(7/25/2015 4:31 PM) [LOG]: rate+|+0
(7/25/2015 4:31 PM) [LOG]: reason+|+invalid_credentials
(7/25/2015 4:31 PM) [LOG]: status+|+FAILED
(7/25/2015 4:31 PM) [LOG]: delay+|+5000
(7/25/2015 4:31 PM) [LOG]: rate+|+150
(7/25/2015 4:31 PM) [LOG]: token+|++BVuB2LjeXyxg0vc5ut2IOnzqIFz4ZmCINgSzhnkXIDMczwddsekHbxjlSRCMpaMvdFGWlAdneJJsBpIjmGgIA==
(7/25/2015 4:31 PM) [LOG]: reason+|+login_rate
(7/25/2015 4:31 PM) [LOG]: status+|+LOGIN
(7/25/2015 4:31 PM) [LOG]: delay+|+5000
(7/25/2015 4:31 PM) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(7/25/2015 4:31 PM) [LOG]: user+|+nitroxenon
(7/25/2015 4:31 PM) [LOG]: idToken+|+eyJhbGciOiJSUzI1NiJ9.eyJsb2wiOlt7InVpZCI6MjI3MDkwNjQ5LCJjdWlkIjoyMjcwOTA2NDksInVuYW1lIjoibml0cm94ZW5vbiIsImNwaWQiOiJOQTEiLCJwaWQiOiJOQTEifV0sImV4cCI6MTQzNzg5OTUxOSwic3ViIjoidXJuOnJpb3Q6cGlkOnYxOk1qSTNNRGt3TmpRNU9rNUJNUSIsInRhZyI6W10sImF1ZCI6ImxvbCIsImlzcyI6Imh0dHBzOlwvXC9nYXMucmlvdGdhbWVzLmNvbSIsImlhdCI6MTQzNzgxMzExOSwiYW1yIjoiY2xpZW50X2Jhc2ljIn0.DlICBfXd-BhkOEn68JxUP38hpmrP8ZG1HChoxorrCZyzcagyx6CO4dmgs1Kc9SgC-YSVAvq0qBLWW3nMKyzNWqR_lNMRX46Fra6tOt1RXSY3WUffAaOCu4ywj4S3bdvm2BZF8XCEdcfN0P3r_waP5llPvqMlWgNOy0haq4Y0p9Een2thrqcR-WR2mW4aQ21hPRgJgZDVCDMMaGg9biL1V6wipqS1ZpFlBZIBFb5cCrmWBkG40hhEvdsr5klo29feBYSQgOOg1I8oocYg6PzwQpR72OTQR-m9kAscHgG8NRljkxAwxqrPtED8XPzsYbcm-2TqaDZEu3ZgBYV_fTGB8w
(7/25/2015 4:31 PM) [LOG]: gasToken+|+{
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "227090649",
  "signature": "DdZZsw4u9zyGpsq51VHiYUGW+USilSpGJisnHqsFUvCEqOl94sBBgl14Av/quPxsop230EHtJ8uK/uLGJnB8daZsw+7wUy2+CG+r7269RwWiysYs3lF8oB6ZXzuENYAwt4P/sbuasZ5DwFxdJVgBEhTjxmiMwlvEObhRRCLo9HDLcTMmZ2ZpN6m18vyOTnec9o7ZXUhXXt86/e6itNRRWsnhSZRjIWZxA/IvQEaQxJt33Wa1QerRIZ2kMmW4+fOZbdelImxnjiXpOPgs+/wTq7OSqI/oPQGFbHHwtQDz9/9o8f/cnrIWl8S+ZmkLCAt6CKA9AiyQKWlZodxrpFPJIg==",
  "summoner_name": null,
  "date_time": 1437813119255,
  "pvpnet_account_id": 227090649
}
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: Invalid login.
(7/25/2015 4:31 PM) [EXCEPTION]: 
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: Invalid login.
(7/25/2015 4:31 PM) [EXCEPTION]: 
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: Invalid login.
(7/25/2015 4:31 PM) [EXCEPTION]: 
(7/25/2015 4:31 PM) [EXCEPTION]: A first chance exception was thrown
(7/25/2015 4:31 PM) [EXCEPTION]: Invalid login.
(7/25/2015 4:31 PM) [EXCEPTION]: 
(7/25/2015 4:31 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(7/25/2015 4:31 PM) [UNHANDLEDEXCEPTION]: Invalid login.
(7/25/2015 4:31 PM) [UNHANDLEDEXCEPTION]: 
```

**Comment by NitroXenon** [comment]
Crash at : 
RtmpSharp.Net.RtmpClient.LoginAsync (Line 694)
LoginPage.xaml.cs (Line 503)

**Comment by eddy5641** [comment]
Can you write that line from loginpage

**Comment by eddy5641** [comment]
Or which branch

**Comment by NitroXenon** [comment]
in multiuser-client branch

**Comment by NitroXenon** [comment]
throws "RtmpSharp.Messaging.InvocationException"

**Comment by nairaner** [comment]
New login method is case-sensitive for the login username or it should be always lowercase

**Comment by NitroXenon** [comment]
@nairaner Yeah lower case fixed the problem.
