### ISSUE TITLE
RMTP? UnhandledException

### ISSUE THREAD

**Issue by horato** [SightstoneOfficial/LegendaryClient#434]
What kind of stack trace is this? -.-

(27.9.2015 8:55) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27.9.2015 8:55) [UNHANDLEDEXCEPTION]: Požadovaný název je platný, ale nebyla nalezena žádná data požadovaného typu
(27.9.2015 8:55) [UNHANDLEDEXCEPTION]:    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at RtmpSharp.Net.RtmpClient.<RecreateConnection>d__19.MoveNext() in c:\Users\Tom\Documents\Visual Studio 2013\Projects\LegendaryClient\rtmp-sharp\Net\RtmpClient.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegendaryClient.Logic.Client.<RiotConnection_Disconnected>d__62.MoveNext() in c:\Users\Tom\Documents\Visual Studio 2013\Projects\LegendaryClient\LegendaryClient\Logic\Client.cs:line 1599
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by secretdataz** [comment]
```
at LegendaryClient.Logic.Client
```

Are you sure you are using the latest build?
We dropped entire LegendaryClient package and renamed it to Sightstone long time ago.

**Comment by horato** [comment]
Its fresh download from like week ago, master branch tho.

**Comment by nairaner** [comment]
We now work on multiuser-client branch

**Comment by secretdataz** [comment]
we'll merge to master when things are done.
"things" refer to https://github.com/LegendaryClient/LegendaryClient/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+4.0%22

**Comment by horato** [comment]
well thank you! thats what I was looking for ^^
