### ISSUE TITLE
Opening Tabs(Champ, Skins)

### ISSUE THREAD

**Issue by Lolr** [SightstoneOfficial/LegendaryClient#86]
Champion : 
(27/10/2014 23:08) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:08) [LOG]: LegendaryClient Started Up Successfully
(27/10/2014 23:08) [LOG]: Starting Patcher
(27/10/2014 23:08) [LOG]: DataDragon Version: 4.18.1
(27/10/2014 23:08) [LOG]: Current DataDragon Version: 4.18.1
(27/10/2014 23:08) [LOG]: DDragon Version (LOL Version) = 4.18.1
(27/10/2014 23:08) [LOG]: Client Version: 4.18.1
(27/10/2014 23:08) [LOG]: Air Assets Version: 0.0.1.115
(27/10/2014 23:08) [LOG]: Current Air Assets Version: 0.0.1.115
(27/10/2014 23:08) [LOG]: Trying to detect League of Legends GameClient
(27/10/2014 23:08) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(27/10/2014 23:08) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(27/10/2014 23:08) [LOG]: Checking if League of Legends is Up-To-Date
(27/10/2014 23:08) [LOG]: League of Legends is Up-To-Date
(27/10/2014 23:08) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:08) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:08) [EXCEPTION]: An invalid IP address was specified.
(27/10/2014 23:08) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(27/10/2014 23:08) [LOG]: Connected and logged in asMrBelgio
(27/10/2014 23:08) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:08) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:08) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:08) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:08) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:08) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(27/10/2014 23:08) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:08) [EXCEPTION]: Application identity is not set.
(27/10/2014 23:08) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(27/10/2014 23:10) [LOG]: Preforming LCDSHeartBeat
(27/10/2014 23:10) [LOG]: Preforming LCDSHeartBeat
(27/10/2014 23:11) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:11) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:11) [EXCEPTION]:    at LegendaryClient.Windows.Profile.Champions.<Update>b__0(ChampionDTO x, ChampionDTO y)
(27/10/2014 23:11) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:11) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:11) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
(27/10/2014 23:11) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:11) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:11) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.Profile.Champions.<Update>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(27/10/2014 23:11) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 23:11) [UNHANDLEDEXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:11) [UNHANDLEDEXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.Profile.Champions.<Update>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

Skins : 
(27/10/2014 23:20) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:20) [LOG]: LegendaryClient Started Up Successfully
(27/10/2014 23:20) [LOG]: Starting Patcher
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(27/10/2014 23:20) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(27/10/2014 23:20) [LOG]: DataDragon Version: 4.18.1
(27/10/2014 23:20) [LOG]: Current DataDragon Version: 4.18.1
(27/10/2014 23:20) [LOG]: DDragon Version (LOL Version) = 4.18.1
(27/10/2014 23:20) [LOG]: Client Version: 4.18.1
(27/10/2014 23:20) [LOG]: Air Assets Version: 0.0.1.115
(27/10/2014 23:20) [LOG]: Current Air Assets Version: 0.0.1.115
(27/10/2014 23:20) [LOG]: Trying to detect League of Legends GameClient
(27/10/2014 23:20) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(27/10/2014 23:20) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(27/10/2014 23:20) [LOG]: Checking if League of Legends is Up-To-Date
(27/10/2014 23:20) [LOG]: League of Legends is Up-To-Date
(27/10/2014 23:20) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: An invalid IP address was specified.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(27/10/2014 23:20) [LOG]: Connected and logged in asMrBelgio
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Application identity is not set.
(27/10/2014 23:20) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:20) [EXCEPTION]:    at LegendaryClient.Windows.Profile.Skins.<Update>b__0(ChampionDTO x, ChampionDTO y)
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:20) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:20) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.Profile.Skins.<Update>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.Profile.Skins.<Update>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

Other summoner's profiles : 
(27/10/2014 23:20) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:20) [LOG]: LegendaryClient Started Up Successfully
(27/10/2014 23:20) [LOG]: Starting Patcher
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(27/10/2014 23:20) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(27/10/2014 23:20) [LOG]: DataDragon Version: 4.18.1
(27/10/2014 23:20) [LOG]: Current DataDragon Version: 4.18.1
(27/10/2014 23:20) [LOG]: DDragon Version (LOL Version) = 4.18.1
(27/10/2014 23:20) [LOG]: Client Version: 4.18.1
(27/10/2014 23:20) [LOG]: Air Assets Version: 0.0.1.115
(27/10/2014 23:20) [LOG]: Current Air Assets Version: 0.0.1.115
(27/10/2014 23:20) [LOG]: Trying to detect League of Legends GameClient
(27/10/2014 23:20) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(27/10/2014 23:20) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(27/10/2014 23:20) [LOG]: Checking if League of Legends is Up-To-Date
(27/10/2014 23:20) [LOG]: League of Legends is Up-To-Date
(27/10/2014 23:20) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: An invalid IP address was specified.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(27/10/2014 23:20) [LOG]: Connected and logged in asMrBelgio
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Application identity is not set.
(27/10/2014 23:20) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:20) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:20) [EXCEPTION]:    at LegendaryClient.Windows.Profile.MatchHistory.GamesListView_SelectionChanged(Object sender, SelectionChangedEventArgs e)
(27/10/2014 23:20) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:20) [EXCEPTION]: Exception has been thrown by the target of an invocation.
(27/10/2014 23:20) [EXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]: Exception has been thrown by the target of an invocation.
(27/10/2014 23:20) [UNHANDLEDEXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

**Comment by juaoose** [comment]
I can not open profile tab since it will crash.

**Comment by eddy5641** [comment]
will work on

**Comment by eddy5641** [comment]
What region are you on

**Comment by juaoose** [comment]
LAN

**Comment by Dispersia** [comment]
Is it still doing this or did one of the changes fix it?

**Comment by juaoose** [comment]
I seem not to have rtmp

Yup, that.

**Comment by Dispersia** [comment]
Wait, what do you mean exactly you don't have rtmp?

**Comment by juaoose** [comment]
Well, I don't have a compiled rtmp-sharp to compile LC

**Comment by horato** [comment]
You can always download it from the cool grill astralfoxy :P https://github.com/astralfoxy/rtmp-sharp

**Comment by juaoose** [comment]
I'll do it later so that I can compile it myself =) (Not that I know plenty
of C Sharp anyway)

@Dispersia , tested the latest release, profile tab continues to crash.
This are the logs for the session in which I logged in and then went to
profile tab, the region is LAN.}
http://pastebin.com/vCg4zUNR

**Comment by Dispersia** [comment]
Actually I just thought of why it would be doing this. What is the name of the person it's crashing on? There prob isn't a check if the array is full or not.

**Comment by juaoose** [comment]
Juaoose

**Comment by nairaner** [comment]
So I got the same problem and it seems to be caused by old gamestats file.

```
(11/26/2014 3:46 PM) [LOG]: LegendaryClient Has Finished Patching
(11/26/2014 3:46 PM) [LOG]: LegendaryClient Started Up Successfully
(11/26/2014 3:46 PM) [LOG]: Starting Patcher
(11/26/2014 3:47 PM) [EXCEPTION]: A first chance exception was thrown
(11/26/2014 3:47 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(11/26/2014 3:47 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(11/26/2014 3:47 PM) [LOG]: DataDragon Version: 4.20.1
(11/26/2014 3:47 PM) [LOG]: Current DataDragon Version: 4.20.1
(11/26/2014 3:47 PM) [LOG]: DDragon Version (LOL Version) = 4.20.1
(11/26/2014 3:47 PM) [LOG]: Client Version: 4.20.1
(11/26/2014 3:47 PM) [LOG]: Air Assets Version: 0.0.1.119
(11/26/2014 3:47 PM) [LOG]: Current Air Assets Version: 0.0.1.119
(11/26/2014 3:47 PM) [LOG]: Trying to detect League of Legends GameClient
(11/26/2014 3:47 PM) [LOG]: League of Legends is located at: C:/Riot Games/League of Legends
(11/26/2014 3:47 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.68
(11/26/2014 3:47 PM) [LOG]: Checking if League of Legends is Up-To-Date
(11/26/2014 3:47 PM) [LOG]: League of Legends is Up-To-Date
(11/26/2014 3:47 PM) [LOG]: LegendaryClient Has Finished Patching
(11/26/2014 3:47 PM) [PVPNETERROR]: Receive
(11/26/2014 3:47 PM) [PVPNETERROR]: 
(11/26/2014 3:47 PM) [EXCEPTION]: A first chance exception was thrown
(11/26/2014 3:47 PM) [EXCEPTION]: An invalid IP address was specified.
(11/26/2014 3:47 PM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(11/26/2014 3:47 PM) [LOG]: Connected and logged in as Nairaner
(11/26/2014 3:47 PM) [EXCEPTION]: A first chance exception was thrown
(11/26/2014 3:47 PM) [EXCEPTION]: Application identity is not set.
(11/26/2014 3:47 PM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(11/26/2014 3:47 PM) [PVPNETERROR]: Receive
(11/26/2014 3:47 PM) [PVPNETERROR]: No Game for player 28315904 was found in the system!
(11/26/2014 3:48 PM) [EXCEPTION]: A first chance exception was thrown
(11/26/2014 3:48 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(11/26/2014 3:48 PM) [EXCEPTION]:    at LegendaryClient.Windows.Profile.Skins.<Update>b__0(ChampionDTO x, ChampionDTO y) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\Windows\Profile\Skins.xaml.cs:line 32
(11/26/2014 3:48 PM) [EXCEPTION]: A first chance exception was thrown
(11/26/2014 3:48 PM) [EXCEPTION]: Failed to compare two elements in the array.
(11/26/2014 3:48 PM) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
```

Juaoose can you try manually updating the gamestats and see if it fixes the problem?
http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/0.0.1.119/files/assets/data/gameStats/gameStats_en_US.sqlite

**Comment by juaoose** [comment]
It didn't fix the problem, just tested. 

Log: http://pastebin.com/CRC9SjRU

**Comment by nairaner** [comment]
But did it fix the crash on champions/skins page, the crash you got is connected to something else

**Comment by juaoose** [comment]
Well I can get to skins and it seems to work but it still crashed because you need to go through the main profile window.

**Comment by eddy5641** [comment]
Added try {} and catch{}

**Comment by nairaner** [comment]
I added catch for profile data, but we still need to figure out why profiles on LAN arent working

**Comment by juaoose** [comment]
Everything in Profile tab is working when its used for yourself, it crashes when you try to open a friends profile right clicking from friends list (but searching his name actually works so the problem should be a line or a call)

Here's a log for right click >view profile:
http://pastebin.com/saVRJuzd
And I don't really know if it is not finished but trying to see champion stats crashes:
http://pastebin.com/4HLMSQN0

**Comment by nairaner** [comment]
Can you join our chat? http://kiwiirc.com/client/irc.freenode.net/#LegendaryClient

**Comment by horato** [comment]
Looks like this is either fixed or the thread just died. If you still have this problem feel free to let us know. I am closing this for now.
